import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function Admin() {
  const sb=await createClient();
  const {data:{user}}=await sb.auth.getUser();
  if(!user) redirect('/');
  const {data:isAdmin}=await sb.rpc('is_admin');
  if(!isAdmin) redirect('/dashboard');
  const [{count:profiles},{count:attempts},{count:missions},{count:completed},{count:presets},{data:first},{data:settings},{data:catalog}]=await Promise.all([
    sb.from('profiles').select('*',{count:'exact',head:true}),sb.from('decision_attempts').select('*',{count:'exact',head:true}),sb.from('missions').select('*',{count:'exact',head:true}).eq('status','published'),sb.from('mission_progress').select('*',{count:'exact',head:true}).eq('status','completed'),sb.from('game_visual_presets').select('*',{count:'exact',head:true}).eq('active',true),sb.from('mission_catalog').select('mission_id,title').eq('status','published').order('sequence_no').limit(1).maybeSingle(),sb.from('game_runtime_settings').select('*').eq('id',1).maybeSingle(),sb.from('mission_catalog').select('mission_id,title,sequence_no,status').eq('status','published').order('sequence_no').limit(6)
  ]);
  return <main className="adminShell">
    <section className="adminHero"><div><div className="ey">JURISQUEST CONTROL • COMMERCIAL BUILD</div><h1>Painel de Operações</h1><p>Conteúdo, direção visual, acesso e telemetria em uma única camada administrativa.</p></div><div className="adminHeroActions">{first&&<a className="btn primary" href={`/game/${first.mission_id}`}>Testar runtime</a>}<a className="btn" href="/dashboard">Área do aluno</a><a className="btn" href="/reset-password">Minha senha</a></div></section>
    <section className="adminMetrics"><div><small>USUÁRIOS</small><strong>{profiles??0}</strong><span>perfis registrados</span></div><div><small>MISSÕES</small><strong>{missions??0}</strong><span>publicadas</span></div><div><small>TENTATIVAS</small><strong>{attempts??0}</strong><span>decisões respondidas</span></div><div><small>CONCLUSÕES</small><strong>{completed??0}</strong><span>missões finalizadas</span></div></section>
    <section className="adminModules"><a className="adminModule featured" href="/admin/visual"><span className="moduleIcon">◇</span><div><small>DIREÇÃO DE ARTE</small><h2>Visual Studio</h2><p>{presets??0} presets ativos. Controle noite, dia, chuva, interiores, personagens e qualidade do renderer.</p><b>Abrir sistema visual →</b></div></a><div className="adminModule"><span className="moduleIcon">✦</span><div><small>GERAÇÃO DE CONTEÚDO</small><h2>Mission Agent</h2><p>Contrato visual V3 preparado para o agente que transformará edital em missões.</p><b>Schema: {settings?.agent_schema_version||'jurisquest.mission.v3-visual'}</b></div></div><div className="adminModule"><span className="moduleIcon">⌁</span><div><small>RUNTIME</small><h2>Engine Settings</h2><p>Desktop <b>{settings?.renderer_quality||'high'}</b> • mobile <b>{settings?.mobile_quality||'balanced'}</b> • UI <b>{settings?.ui_theme||'anime_noir'}</b>.</p><a href="/admin/visual">Ajustar renderer →</a></div></div><div className="adminModule"><span className="moduleIcon">◎</span><div><small>ACESSO E PLANOS</small><h2>Usuários</h2><p>RLS e grants controlam trial, acesso premium e permissões administrativas.</p><span className="adminBadge">PROTEGIDO NO BANCO</span></div></div></section>
    <section className="adminPanel"><div className="panelHead"><div><div className="ey">CONTEÚDO ATIVO</div><h2>Campanha publicada</h2></div><span className="adminBadge">{catalog?.length||0} NO PAINEL</span></div><div className="missionRows">{(catalog||[]).map((m:any)=><div className="missionRow" key={m.mission_id}><span className="seq">{String(m.sequence_no||0).padStart(2,'0')}</span><strong>{m.title}</strong><div/><a href={`/game/${m.mission_id}`}>Jogar</a></div>)}</div></section>
  </main>;
}
