'use server';
import { headers } from 'next/headers';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
export async function login(formData:FormData){const sb=await createClient();const email=String(formData.get('email')||'').trim().toLowerCase();const password=String(formData.get('password')||'');const{error}=await sb.auth.signInWithPassword({email,password});if(error)redirect('/?error='+encodeURIComponent('Não foi possível entrar. Confira e-mail e senha ou use Recuperar senha.'));redirect('/dashboard')}
export async function register(formData:FormData){const sb=await createClient();const display_name=String(formData.get('name')||'').trim();const email=String(formData.get('email')||'').trim().toLowerCase();const password=String(formData.get('password')||'');const confirm=String(formData.get('confirm')||'');if(display_name.length<2||!email.includes('@')||password.length<8||password!==confirm)redirect('/signup?error=1');const{data,error}=await sb.functions.invoke('public-signup',{body:{email,password,display_name}});if(error||data?.error)redirect('/signup?error=1');const auth=await sb.auth.signInWithPassword({email,password});if(auth.error)redirect('/?error='+encodeURIComponent('Conta criada. Faça login.'));redirect('/dashboard')}
export async function logout(){const sb=await createClient();await sb.auth.signOut();redirect('/')}
export async function requestReset(formData:FormData){const sb=await createClient();const email=String(formData.get('email')||'').trim().toLowerCase();const h=await headers();const host=h.get('x-forwarded-host')||h.get('host');const proto=h.get('x-forwarded-proto')||'https';const origin=`${proto}://${host}`;const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:`${origin}/auth/callback?next=/reset-password`});redirect('/forgot-password?sent='+(error?'0':'1'))}
export async function updatePassword(formData:FormData){const sb=await createClient();const p1=String(formData.get('password')||''),p2=String(formData.get('confirm')||'');if(p1.length<8||p1!==p2)redirect('/reset-password?error=1');const{error}=await sb.auth.updateUser({password:p1});if(error)redirect('/reset-password?error=1');redirect('/dashboard?password=updated')}
