'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { PALETTES, svgUri, chibiSvg, objectSvg, sceneSvg } from '@/lib/game/studio-assets';
import { STUDIO_CSS } from '@/lib/game/studio-css';

type Props={missionId:string;mission:any;userId:string;initialCharacter?:any;initialProgress?:any;runtimeSettings?:any};
type Runtime={stageId:string;facts:string[];decisions:string[];wrong:string[];attemptCounts:Record<string,number>;started:boolean;completed:boolean};
type Near={type:'actor'|'object';id:string;label:string}|null;
type Overlay=null|{type:'brief'}|{type:'fact';fact:any}|{type:'decision';d:any}|{type:'feedback';d:any;choice:any;correct:boolean}|{type:'transition';next:string;data:any}|{type:'complete';score:number};

const DW=1200,DH=760;

export default function GameRuntimeSafe({missionId,mission,userId,initialCharacter,initialProgress,runtimeSettings}:Props){
  const stages=useMemo(()=>[...(mission.stages||[])].sort((a:any,b:any)=>(a.order||0)-(b.order||0)),[mission]);
  const resume=initialProgress?.runtime_state||{};
  const initial:Runtime={stageId:resume.stageId||initialProgress?.current_stage||stages[0]?.id||'',facts:resume.facts||initialProgress?.facts||[],decisions:resume.decisions||[],wrong:resume.wrong||initialProgress?.mistakes||[],attemptCounts:resume.attemptCounts||initialProgress?.decisions||{},started:resume.started??!!initialProgress,completed:initialProgress?.status==='completed'};
  const [runtime,setRuntime]=useState(initial),rr=useRef(initial);
  const [near,setNear]=useState<Near>(null),nr=useRef<Near>(null);
  const [overlay,setOverlay]=useState<Overlay>(initial.started?null:{type:'brief'});
  const [dialog,setDialog]=useState<any>(null),[notebook,setNotebook]=useState(false),[progressOpen,setProgressOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[whyOpen,setWhyOpen]=useState(false);
  const [ready,setReady]=useState(false),[cloud,setCloud]=useState('Sincronizando'),[engineError,setEngineError]=useState(''),[distance,setDistance]=useState<number|null>(null);
  const sceneRef=useRef<any>(null),host=useRef<HTMLDivElement>(null),sb=useRef(createClient()),saveChain=useRef<Promise<void>>(Promise.resolve());
  const stage=stages.find((s:any)=>s.id===runtime.stageId)||stages[0],stageIndex=Math.max(0,stages.findIndex((s:any)=>s.id===stage?.id));
  const character=initialCharacter||{character_name:'Jogador',role_title:'Candidato',archetype:'operational'};
  useEffect(()=>{rr.current=runtime},[runtime]);useEffect(()=>{nr.current=near},[near]);
  const hasFact=(id:string,r=rr.current)=>r.facts.includes(id),hasDecision=(id:string,r=rr.current)=>r.decisions.includes(id),getDecision=(id:string)=>(mission.decisions||[]).find((d:any)=>d.id===id);
  const objectiveDone=(o:any,r=rr.current)=>o?.type==='actor'||o?.type==='object'?hasFact(o.target,r):o?.type==='decision'?hasDecision(o.target,r):false;
  const currentObjective=(r=rr.current)=>{const s=stages.find((x:any)=>x.id===r.stageId);return(s?.objectives||[]).find((o:any)=>o.type==='advance'||!objectiveDone(o,r))||null};
  const decisionReady=(d:any,r=rr.current)=>(d?.requires_facts||[]).every((f:string)=>hasFact(f,r))&&(d?.depends_on||[]).every((x:string)=>hasDecision(x,r));
  const overallProgress=(r=rr.current)=>{const os=stages.flatMap((s:any)=>(s.objectives||[]).filter((o:any)=>o.type!=='advance'));return os.length?Math.round(os.filter((o:any)=>objectiveDone(o,r)).length/os.length*100):0};
  const objective=currentObjective(runtime);
  const targetEntity=useMemo(()=>{if(!objective||!stage)return null;if(objective.type==='actor')return(stage.actors||[]).find((x:any)=>x.id===objective.target)||null;if(objective.type==='object')return(stage.objects||[]).find((x:any)=>x.id===objective.target)||null;return null},[objective,stage]);
  useEffect(()=>setWhyOpen(false),[runtime.stageId,objective?.target,objective?.type]);

  function persist(next:Runtime,complete=false,score:number|null=null){saveChain.current=saveChain.current.then(async()=>{setCloud('Salvando…');const{error}=await sb.current.from('mission_progress').upsert({user_id:userId,mission_id:missionId,status:complete?'completed':'in_progress',current_stage:next.stageId,progress_percent:complete?100:overallProgress(next),score_first_try:complete?score:null,score_best:complete?score:null,mistakes:next.wrong,facts:next.facts,decisions:next.attemptCounts,runtime_state:next,started_at:initialProgress?.started_at||new Date().toISOString(),completed_at:complete?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:'user_id,mission_id'});setCloud(error?'Falha ao salvar':'Progresso salvo');if(error)console.error(error)}).catch(e=>{console.error(e);setCloud('Falha ao salvar')});return saveChain.current}
  function apply(next:Runtime,persistNow=true){rr.current=next;setRuntime(next);if(persistNow)void persist(next)}
  function registerFact(f:any){if(!f?.id||hasFact(f.id)){setOverlay(null);return}const next={...rr.current,facts:[...rr.current.facts,f.id]};apply(next);setOverlay({type:'fact',fact:f})}
  function interactNear(){const n=nr.current;if(!n)return;const s=stages.find((x:any)=>x.id===rr.current.stageId);if(n.type==='actor'){const a=(s?.actors||[]).find((x:any)=>x.id===n.id);if(a)setDialog({actor:a,index:0})}else{const o=(s?.objects||[]).find((x:any)=>x.id===n.id);if(o?.fact)registerFact(o.fact)}}
  async function answer(d:any,i:number){const c=d.choices?.[i];if(!c)return;const r=rr.current,attempt=(r.attemptCounts[d.id]||0)+1,correct=!!c.correct,wrong=!correct&&attempt===1&&!r.wrong.includes(d.id)?[...r.wrong,d.id]:r.wrong,base={...r,wrong,attemptCounts:{...r.attemptCounts,[d.id]:attempt}};setCloud('Registrando decisão…');const{error}=await sb.current.from('decision_attempts').insert({user_id:userId,mission_id:missionId,decision_id:d.id,attempt_no:attempt,selected_index:i,selected_text:c.text,correct,mode:'mission',feedback_snapshot:d.feedback||{}});if(error){setCloud('Falha ao registrar decisão');return}const next=correct?{...base,decisions:base.decisions.includes(d.id)?base.decisions:[...base.decisions,d.id]}:base;apply(next);setOverlay({type:'feedback',d,choice:c,correct})}
  async function finish(){const r=rr.current,total=Math.max(1,(mission.decisions||[]).length),score=Math.max(0,Math.round((total-r.wrong.length)/total*100)),next={...r,completed:true};rr.current=next;setRuntime(next);await persist(next,true,score);setOverlay({type:'complete',score})}
  function primary(){const r=rr.current,s=stages.find((x:any)=>x.id===r.stageId),o=currentObjective(r);if(o?.type==='actor'||o?.type==='object'){const n=nr.current;if(n&&n.type===o.type&&n.id===o.target)interactNear();return}if(o?.type==='decision'){const d=getDecision(o.target);if(decisionReady(d,r))setOverlay({type:'decision',d});return}if(o?.type==='advance'){const i=stages.findIndex((x:any)=>x.id===s?.id),next=stages[i+1];if(next)setOverlay({type:'transition',next:next.id,data:s?.transition||{}});return}if(!o&&s?.final)void finish()}
  function goStage(id:string){const next={...rr.current,stageId:id};apply(next);setOverlay(null);sceneRef.current?.buildStage?.(stages.find((s:any)=>s.id===id))}

  const nearIsTarget=!!(objective&&(objective.type==='actor'||objective.type==='object')&&near&&near.type===objective.type&&near.id===objective.target),decisionCanOpen=objective?.type==='decision'?decisionReady(getDecision(objective.target),runtime):false;
  const primaryEnabled=ready&&(nearIsTarget||(objective?.type==='decision'&&decisionCanOpen)||objective?.type==='advance'||(!objective&&stage?.final)),targetName=targetEntity?.name||objective?.title||'';
  const guidance=!ready?'Preparando cenário':objective?.type==='actor'?(nearIsTarget?`Fale com ${targetName}`:`Vá até ${targetName}`):objective?.type==='object'?(nearIsTarget?(targetEntity?.interaction_text||`Examine ${targetName}`):`Vá até ${targetName}`):objective?.type==='decision'?(decisionCanOpen?objective.title:'Complete as evidências anteriores'):objective?.type==='advance'?(objective.title||'Avance para a próxima etapa'):(!objective&&stage?.final?'Concluir missão':'Explore o cenário');

  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.repeat)return;const k=e.key.toLowerCase();if(k==='j'&&!overlay&&!dialog){setNotebook(v=>!v);setProgressOpen(false);setMenuOpen(false)}else if(k==='p'&&!overlay&&!dialog){setProgressOpen(v=>!v);setNotebook(false);setMenuOpen(false)}else if(e.key==='Escape'){if(notebook)setNotebook(false);else if(progressOpen)setProgressOpen(false);else if(menuOpen)setMenuOpen(false);else if(dialog)setDialog(null);else if(!overlay)setMenuOpen(true)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[overlay,dialog,notebook,progressOpen,menuOpen]);

  useEffect(()=>{let game:any,cancelled=false;(async()=>{try{const mod:any=await import('phaser');if(cancelled||!host.current)return;const P:any=mod.default||mod;class SafeScene extends P.Scene{
    player:any;actors:Record<string,any>={};objects:Record<string,any>={};cursors:any;keys:any;worldW=DW;worldH=DH;isDesktop=true;beacon:any;guide:any;lastNear='';lastDistance=-1;
    constructor(){super('safe')}
    preload(){this.load.image('bg-parking',svgUri(sceneSvg('parking_night')));this.load.image('bg-station',svgUri(sceneSvg('police_station')));this.load.image('bg-court',svgUri(sceneSvg('courtroom')));for(const k of Object.keys(PALETTES))this.load.image(`char-${k}`,svgUri(chibiSvg(k)));this.load.image('char-player',svgUri(chibiSvg(character.archetype||'operational','player')));this.load.image('obj-camera',svgUri(objectSvg('camera')));this.load.image('obj-evidence',svgUri(objectSvg('evidence')));this.load.image('obj-document',svgUri(objectSvg('document')))}
    create(){sceneRef.current=this;this.cursors=this.input.keyboard?.createCursorKeys();this.keys=this.input.keyboard?.addKeys('W,A,S,D,SHIFT,E,ENTER');this.input.keyboard?.on('keydown-E',primary);this.input.keyboard?.on('keydown-ENTER',primary);this.buildStage(stages.find((x:any)=>x.id===rr.current.stageId)||stages[0]);this.scale.on('resize',()=>this.buildStage(stages.find((x:any)=>x.id===rr.current.stageId)||stages[0]));setReady(true);setCloud('Progresso salvo')}
    mapX(x:number){const p=Math.max(30,this.worldW*.025);return p+(x/DW)*(this.worldW-p*2)}
    mapY(y:number){const t=Math.max(80,this.worldH*.08),b=Math.max(80,this.worldH*.09);return t+(y/DH)*(this.worldH-t-b)}
    config(){this.isDesktop=this.scale.width>=900;this.worldW=this.isDesktop?this.scale.width:DW;this.worldH=this.isDesktop?this.scale.height:DH;this.physics.world.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setZoom(this.isDesktop?1:Number(runtimeSettings?.settings?.camera_zoom_mobile||.86));if(this.isDesktop){this.cameras.main.stopFollow();this.cameras.main.setScroll(0,0)}}
    bgKey(s:any){return s.environment==='police_station'?'bg-station':s.environment==='courtroom'?'bg-court':'bg-parking'}
    label(name:string,role:string){const c=this.add.container(0,0).setDepth(1200),w=Math.max(118,Math.min(210,name.length*8+38)),bg=this.add.rectangle(0,0,w,38,0x061820,.92).setStrokeStyle(1,0x49636d,.7),t=this.add.text(0,-5,name,{fontFamily:'Inter,Arial',fontSize:'12px',fontStyle:'bold',color:'#fff'}).setOrigin(.5),r=this.add.text(0,10,role,{fontFamily:'Inter,Arial',fontSize:'8px',fontStyle:'bold',color:'#83d9e8'}).setOrigin(.5);c.add([bg,t,r]);return c}
    actor(def:any,isPlayer=false){const x=this.mapX(def.position?.x||600),y=this.mapY(def.position?.y||650),key=isPlayer?'char-player':`char-${def.visual?.archetype||def.style||'civilian'}`,img=this.physics.add.image(x,y,key).setOrigin(.5,.86);const scale=Math.max(.38,Math.min(.55,this.worldH/1700));img.setScale(scale);img.body.setSize(70,42);img.body.setCollideWorldBounds(true);img.setDepth(y+20);(img as any).jqLabel=isPlayer?null:this.label(def.name,def.role);return img}
    prop(def:any){const x=this.mapX(def.position?.x||500),y=this.mapY(def.position?.y||300),key=def.kind==='camera'?'obj-camera':def.kind==='evidence'?'obj-evidence':'obj-document',img=this.add.image(x,y,key).setScale(.5).setDepth(y+6);(img as any).jqLabel=this.label(def.name||'Objeto',def.role||'EVIDÊNCIA');(img as any).jqLabel.setVisible(false);return img}
    buildStage(s:any){if(!s)return;this.children.removeAll(true);this.actors={};this.objects={};this.lastNear='';setNear(null);this.config();const bg=this.add.image(this.worldW/2,this.worldH/2,this.bgKey(s));const scale=Math.max(this.worldW/1600,this.worldH/900);bg.setScale(scale).setDepth(-100);this.player=this.actor({position:s.player_spawn||{x:600,y:650}},true);for(const a of s.actors||[])this.actors[a.id]={def:a,go:this.actor(a)};for(const o of s.objects||[])this.objects[o.id]={def:o,go:this.prop(o)};this.beacon=this.add.circle(0,0,22,0xffd75e,.1).setStrokeStyle(3,0xffd75e,.95).setDepth(1500);this.guide=this.add.graphics().setDepth(1240);if(!this.isDesktop)this.cameras.main.startFollow(this.player,true,.12,.12)}
    update(time:number){if(!this.player)return;const blocked=!!overlay||!!dialog||notebook||progressOpen||menuOpen||!rr.current.started;const speed=this.keys?.SHIFT?.isDown?300:200,kx=((this.keys?.D?.isDown||this.cursors?.right?.isDown)?1:0)-((this.keys?.A?.isDown||this.cursors?.left?.isDown)?1:0),ky=((this.keys?.S?.isDown||this.cursors?.down?.isDown)?1:0)-((this.keys?.W?.isDown||this.cursors?.up?.isDown)?1:0),len=Math.hypot(kx,ky);if(!blocked&&len>.05){this.player.body.setVelocity(kx/len*speed,ky/len*speed);this.player.setFlipX(kx<0);this.player.angle=Math.sin(time/90)*1.1}else{this.player.body.setVelocity(0,0);this.player.angle=0}this.player.setDepth(this.player.y+20);const s=stages.find((x:any)=>x.id===rr.current.stageId)||stages[0],o=currentObjective(rr.current),targetId=o&&(o.type==='actor'||o.type==='object')?o.target:null;let target:any=null;for(const[id,e]of Object.entries(this.actors)as any[]){e.go.setDepth(e.go.y+10);if(e.go.jqLabel){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-100;e.go.jqLabel.setVisible(id===targetId||P.Math.Distance.Between(this.player.x,this.player.y,e.go.x,e.go.y)<150)}if(o?.type==='actor'&&id===targetId)target=e.go}for(const[id,e]of Object.entries(this.objects)as any[]){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-70;const active=o?.type==='object'&&id===targetId;e.go.jqLabel.setVisible(active);if(active)target=e.go}this.guide.clear();if(target){this.beacon.setVisible(true);this.beacon.x=target.x;this.beacon.y=target.y-105+Math.sin(time/220)*4;const dx=target.x-this.player.x,dy=target.y-this.player.y,d=Math.hypot(dx,dy),count=Math.min(10,Math.max(4,Math.floor(d/90)));for(let i=1;i<count;i++){const t=i/count;this.guide.fillStyle(0x68e8ff,.55);this.guide.fillCircle(this.player.x+dx*t,this.player.y+dy*t,4)}const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}const radius=Number(runtimeSettings?.settings?.interaction_radius||120);const best:d extends never?never:Near=d<radius?{type:o.type,id:o.target,label:o.type==='actor'?`Falar com ${targetName}`:(targetEntity?.interaction_text||`Examinar ${targetName}`)}:null;const key=best?`${best.type}:${best.id}`:'';if(key!==this.lastNear){this.lastNear=key;setNear(best)}}else{this.beacon.setVisible(false);this.lastDistance=-1;setDistance(null);if(this.lastNear){this.lastNear='';setNear(null)}}}
  }game=new P.Game({type:P.AUTO,parent:host.current,width:window.innerWidth,height:window.innerHeight,transparent:true,physics:{default:'arcade',arcade:{debug:false}},scene:SafeScene,scale:{mode:P.Scale.RESIZE,autoCenter:P.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false,powerPreference:'high-performance'}})}catch(e:any){console.error(e);setEngineError(e?.message||'Falha ao iniciar o motor gráfico.');setCloud('Motor indisponível')}})();return()=>{cancelled=true;try{game?.destroy(true)}catch{}sceneRef.current=null}},[]);

  const notes=runtime.facts.map(id=>stages.flatMap((s:any)=>[...(s.actors||[]),...(s.objects||[])]).find((x:any)=>x.fact?.id===id)?.fact).filter(Boolean),rules=runtime.decisions.map(id=>getDecision(id)).filter(Boolean),errors=runtime.wrong.map(id=>getDecision(id)).filter(Boolean),stageObjectives=stage?.objectives||[];
  return <main className="studioGame"><div ref={host} className="studioCanvas"/><div className="studioHud"><header className="topMission"><div className="brand">JURIS<span>QUEST</span></div><div className="mission"><small>ETAPA {stageIndex+1} DE {stages.length}</small><strong>{mission.title}</strong><span>{stage?.location||stage?.title}</span></div></header><div className="topActions"><button onClick={()=>{setNotebook(true);setProgressOpen(false);setMenuOpen(false)}}><b>▤</b><span>Caderno</span><kbd>J</kbd></button><button onClick={()=>{setProgressOpen(true);setNotebook(false);setMenuOpen(false)}}><b>◎</b><span>Objetivos</span><kbd>P</kbd></button><button onClick={()=>{setMenuOpen(true);setNotebook(false);setProgressOpen(false)}}><b>⚙</b><span>Menu</span><kbd>Esc</kbd></button></div><section className="objectiveCard"><div className="kicker"><i/> OBJETIVO ATUAL</div><h2>{objective?.title||'Etapa concluída'}</h2><p>{objective?.text||(stage?.final?'Finalize a missão.':'Avance para a próxima etapa.')}</p>{objective?.why&&<><button className="why" onClick={()=>setWhyOpen(v=>!v)}>› Por que isso importa?</button>{whyOpen&&<div className="whyText">{objective.why}</div>}</>}</section><section className="guideBar"><div className="guideIcon">!</div><div className="guideText"><b>{guidance}</b><span>{nearIsTarget?'Você está no alcance. Pressione E.':'Siga o marcador luminoso.'}</span></div>{distance&&<div className="distance">{distance} m</div>}{primaryEnabled&&<button onClick={primary}><kbd>E</kbd>{objective?.type==='actor'?'Falar':objective?.type==='object'?'Examinar':'Continuar'}</button>}</section><section className="keys"><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><span>Mover</span></div><div><kbd>Shift</kbd><span>Correr</span></div><div><kbd>E</kbd><span>Interagir</span></div></section><div className={`sync ${cloud.includes('Falha')?'bad':''}`}>{cloud}</div></div>
  {engineError&&<ModalBox eyebrow="ERRO DO MOTOR" title="Não foi possível iniciar"><p>{engineError}</p><a className="mBtn" href="/dashboard">Voltar</a></ModalBox>}
  {overlay?.type==='brief'&&<ModalBox eyebrow={mission.briefing?.eyebrow||'MISSÃO INVESTIGATIVA'} title={mission.title} wide><p className="lead">{mission.briefing?.text||mission.summary}</p><button className="mBtn primary" onClick={()=>{setOverlay(null);const next={...rr.current,started:true};rr.current=next;setRuntime(next);void persist(next)}}>Entrar na ocorrência</button></ModalBox>}
  {dialog&&(()=>{const line=dialog.actor.dialogue?.[dialog.index]||{text:'Sem informação adicional.',choices:['Encerrar']};return <ModalBox eyebrow={dialog.actor.role} title={dialog.actor.name} wide><div className="dialog"><img src={svgUri(chibiSvg(dialog.actor.visual?.archetype||dialog.actor.style||'civilian'))} alt=""/><div><p>{line.text}</p><div className="choices">{(line.choices||['Continuar']).map((c:string,i:number)=><button key={i} onClick={()=>{if(dialog.index<(dialog.actor.dialogue?.length||1)-1)setDialog({...dialog,index:dialog.index+1});else{const f=dialog.actor.fact;setDialog(null);if(f)registerFact(f)}}}><span>{String.fromCharCode(65+i)}</span>{c}</button>)}</div><button className="close" onClick={()=>setDialog(null)}>Encerrar conversa</button></div></div></ModalBox>})()}
  {overlay?.type==='fact'&&<ModalBox eyebrow={overlay.fact.kind||'FATO REGISTRADO'} title={overlay.fact.title}><p>{overlay.fact.text}</p><button className="mBtn primary" onClick={()=>setOverlay(null)}>Continuar</button></ModalBox>}
  {overlay?.type==='decision'&&<ModalBox eyebrow="DECISÃO JURÍDICA" title={overlay.d.title} wide><p className="question">{overlay.d.question}</p><div className="choices">{overlay.d.choices.map((c:any,i:number)=><button key={i} onClick={()=>void answer(overlay.d,i)}><span>{String.fromCharCode(65+i)}</span>{c.text}</button>)}</div></ModalBox>}
  {overlay?.type==='feedback'&&<ModalBox eyebrow={overlay.correct?'BOA ESCOLHA':'INFORMAÇÃO IMPORTANTE'} title={overlay.d.title} wide><div className={`feedback ${overlay.correct?'ok':'warn'}`}>{overlay.choice.feedback}</div><div className="feedbackGrid"><Info label="REGRA" text={overlay.d.feedback?.rule}/><Info label="APLICAÇÃO" text={overlay.d.feedback?.application}/><Info label="BASE LEGAL" text={overlay.d.feedback?.legal_basis}/><Info label="PEGADINHA" text={overlay.d.feedback?.trap}/><Info label="MEMÓRIA" text={overlay.d.feedback?.memory} wide/></div><button className="mBtn primary" onClick={()=>overlay.correct?setOverlay(null):setOverlay({type:'decision',d:overlay.d})}>{overlay.correct?'Consolidar e continuar':'Tentar novamente'}</button></ModalBox>}
  {overlay?.type==='transition'&&<ModalBox eyebrow={overlay.data.label||'TRANSIÇÃO'} title={overlay.data.title||'Próxima etapa'}><p>{overlay.data.text||'A missão avança.'}</p><button className="mBtn primary" onClick={()=>goStage(overlay.next)}>Seguir para a próxima cena</button></ModalBox>}
  {overlay?.type==='complete'&&<ModalBox eyebrow="MISSÃO CONCLUÍDA" title={mission.title}><p>{mission.review_plan?.completion_text}</p><div className="stats"><div><small>PROGRESSO</small><b>100%</b></div><div><small>1ª TENTATIVA</small><b>{overlay.score}%</b></div><div><small>ERROS</small><b>{runtime.wrong.length}</b></div></div><a className="mBtn primary" href="/dashboard">Voltar à campanha</a></ModalBox>}
  {notebook&&<ModalBox eyebrow="CADERNO" title="Fatos, regras e erros" wide><h3>Fatos coletados</h3>{notes.length?notes.map((f:any)=><Note key={f.id} title={f.title} text={f.text}/>):<p>Nenhum fato ainda.</p>}<h3>Regras consolidadas</h3>{rules.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.memory||d.feedback?.rule}/>)}<h3>Erros</h3>{errors.length?errors.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.trap}/>):<p>Nenhum erro de primeira tentativa.</p>}<button className="mBtn" onClick={()=>setNotebook(false)}>Fechar</button></ModalBox>}
  {progressOpen&&<ModalBox eyebrow={`ETAPA ${stageIndex+1} DE ${stages.length}`} title="Objetivos da missão" wide><div className="progressList">{stageObjectives.map((o:any,i:number)=><div className={objectiveDone(o,runtime)?'done':o===objective?'current':''} key={`${o.type}-${o.target||i}`}><span>{objectiveDone(o,runtime)?'✓':i+1}</span><div><b>{o.title}</b><p>{o.text}</p></div></div>)}</div><button className="mBtn" onClick={()=>setProgressOpen(false)}>Fechar</button></ModalBox>}
  {menuOpen&&<ModalBox eyebrow="JOGO PAUSADO" title={mission.title}><p>Seu progresso é salvo automaticamente.</p><div className="choices"><button onClick={()=>setMenuOpen(false)}><span>▶</span>Continuar</button><button onClick={()=>{setMenuOpen(false);setNotebook(true)}}><span>J</span>Abrir caderno</button><button onClick={()=>{setMenuOpen(false);setProgressOpen(true)}}><span>P</span>Ver objetivos</button></div><a className="mBtn" href="/dashboard">Sair para a campanha</a></ModalBox>}
  <style jsx global>{STUDIO_CSS}</style></main>
}
function ModalBox({eyebrow,title,children,wide=false}:{eyebrow:string;title:string;children?:any;wide?:boolean}){return <div className="modal"><section className={`sheet ${wide?'wide':''}`}><span className="ey">{eyebrow}</span><h2>{title}</h2>{children}</section></div>}
function Info({label,text,wide=false}:{label:string;text?:string;wide?:boolean}){if(!text)return null;return <div className={`info ${wide?'wide':''}`}><small>{label}</small><p>{text}</p></div>}
function Note({title,text}:{title:string;text:string;key?:any}){return <div className="note"><b>{title}</b><p>{text}</p></div>}
