'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import type { RuntimeSettings, VisualPreset } from '@/lib/game/visual-contract';
import { PALETTES, svgUri, chibiSvg, objectSvg, sceneSvg } from '@/lib/game/studio-assets';
import { STUDIO_CSS } from '@/lib/game/studio-css';

type Props = {
  missionId: string;
  mission: any;
  userId: string;
  initialCharacter?: any;
  initialProgress?: any;
  visualPresets?: VisualPreset[];
  runtimeSettings?: RuntimeSettings | null;
};

type Runtime = {
  stageId: string;
  facts: string[];
  decisions: string[];
  wrong: string[];
  attemptCounts: Record<string, number>;
  started: boolean;
  completed: boolean;
};

type Near = { type: 'actor' | 'object'; id: string; label: string } | null;
type Overlay =
  | null
  | { type: 'brief' }
  | { type: 'fact'; fact: any }
  | { type: 'decision'; d: any }
  | { type: 'feedback'; d: any; choice: any; correct: boolean }
  | { type: 'transition'; next: string; data: any }
  | { type: 'complete'; score: number };

const DESIGN_W = 1200;
const DESIGN_H = 760;

export default function GameRuntimeStudio({ missionId, mission, userId, initialCharacter, initialProgress, runtimeSettings = null }: Props) {
  const stages = useMemo(() => [...(mission.stages || [])].sort((a: any,b: any)=>(a.order||0)-(b.order||0)), [mission]);
  const resume = initialProgress?.runtime_state || {};
  const first = stages[0]?.id || '';
  const initial: Runtime = { stageId: resume.stageId || initialProgress?.current_stage || first, facts: resume.facts || initialProgress?.facts || [], decisions: resume.decisions || [], wrong: resume.wrong || initialProgress?.mistakes || [], attemptCounts: resume.attemptCounts || initialProgress?.decisions || {}, started: resume.started ?? !!initialProgress, completed: initialProgress?.status === 'completed' };
  const [runtime,setRuntime] = useState(initial); const runtimeRef = useRef(initial);
  const [near,setNear] = useState<Near>(null); const nearRef = useRef<Near>(null);
  const [overlay,setOverlay] = useState<Overlay>(initial.started ? null : {type:'brief'});
  const [dialog,setDialog] = useState<any>(null); const [notebook,setNotebook] = useState(false); const [progressOpen,setProgressOpen] = useState(false); const [whyOpen,setWhyOpen] = useState(false);
  const [ready,setReady] = useState(false); const [cloud,setCloud] = useState('Sincronizando'); const [engineError,setEngineError] = useState(''); const [distance,setDistance] = useState<number|null>(null);
  const host = useRef<HTMLDivElement>(null); const sceneRef = useRef<any>(null); const move = useRef({x:0,y:0}); const sb = useRef(createClient());
  const character = initialCharacter || {character_name:'Jogador',role_title:'Candidato',archetype:'operational'};
  const stage = stages.find((s:any)=>s.id===runtime.stageId) || stages[0]; const stageIndex = Math.max(0, stages.findIndex((s:any)=>s.id===stage?.id));
  useEffect(()=>{runtimeRef.current=runtime},[runtime]); useEffect(()=>{nearRef.current=near},[near]);
  const hasFact=(id:string,r=runtimeRef.current)=>r.facts.includes(id); const hasDecision=(id:string,r=runtimeRef.current)=>r.decisions.includes(id); const getDecision=(id:string)=>(mission.decisions||[]).find((d:any)=>d.id===id);
  const objectiveDone=(o:any,r=runtimeRef.current)=>o?.type==='actor'||o?.type==='object'?hasFact(o.target,r):o?.type==='decision'?hasDecision(o.target,r):false;
  const currentObjective=(r=runtimeRef.current)=>{const s=stages.find((x:any)=>x.id===r.stageId);return (s?.objectives||[]).find((o:any)=>o.type==='advance'||!objectiveDone(o,r))||null};
  const decisionReady=(d:any,r=runtimeRef.current)=>(d?.requires_facts||[]).every((f:string)=>hasFact(f,r))&&(d?.depends_on||[]).every((x:string)=>hasDecision(x,r));
  const overallProgress=(r=runtimeRef.current)=>{const os=stages.flatMap((s:any)=>(s.objectives||[]).filter((o:any)=>o.type!=='advance'));return os.length?Math.round(os.filter((o:any)=>objectiveDone(o,r)).length/os.length*100):0};
  const objective=currentObjective(runtime);
  const targetEntity=useMemo(()=>{if(!objective||!stage)return null;if(objective.type==='actor')return(stage.actors||[]).find((x:any)=>x.id===objective.target)||null;if(objective.type==='object')return(stage.objects||[]).find((x:any)=>x.id===objective.target)||null;return null},[objective,stage]);
  useEffect(()=>{setWhyOpen(false)},[runtime.stageId,objective?.target,objective?.type]);

  async function save(next:Runtime,complete=false,score:number|null=null){setCloud('Salvando…');const{error}=await sb.current.from('mission_progress').upsert({user_id:userId,mission_id:missionId,status:complete?'completed':'in_progress',current_stage:next.stageId,progress_percent:complete?100:overallProgress(next),score_first_try:complete?score:null,score_best:complete?score:null,mistakes:next.wrong,facts:next.facts,decisions:next.attemptCounts,runtime_state:next,started_at:initialProgress?.started_at||new Date().toISOString(),completed_at:complete?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:'user_id,mission_id'});setCloud(error?'Falha ao salvar':'Progresso salvo');if(error)console.error(error)}
  function apply(next:Runtime,persist=true){runtimeRef.current=next;setRuntime(next);if(persist)void save(next)}
  function registerFact(f:any){if(!f?.id||hasFact(f.id)){setOverlay(null);return}const next={...runtimeRef.current,facts:[...runtimeRef.current.facts,f.id]};apply(next);setOverlay({type:'fact',fact:f})}
  function interactNear(){const n=nearRef.current;if(!n)return;const s=stages.find((x:any)=>x.id===runtimeRef.current.stageId);if(n.type==='actor'){const a=(s?.actors||[]).find((x:any)=>x.id===n.id);if(a)setDialog({actor:a,index:0})}else{const o=(s?.objects||[]).find((x:any)=>x.id===n.id);if(o?.fact)registerFact(o.fact)}}
  async function answer(d:any,i:number){const c=d.choices?.[i];if(!c)return;const r=runtimeRef.current,attempt=(r.attemptCounts[d.id]||0)+1,correct=!!c.correct,wrong=!correct&&attempt===1&&!r.wrong.includes(d.id)?[...r.wrong,d.id]:r.wrong,base={...r,wrong,attemptCounts:{...r.attemptCounts,[d.id]:attempt}};await sb.current.from('decision_attempts').insert({user_id:userId,mission_id:missionId,decision_id:d.id,attempt_no:attempt,selected_index:i,selected_text:c.text,correct,mode:'mission',feedback_snapshot:d.feedback||{}});const next=correct?{...base,decisions:base.decisions.includes(d.id)?base.decisions:[...base.decisions,d.id]}:base;apply(next);setOverlay({type:'feedback',d,choice:c,correct})}
  async function finish(){const r=runtimeRef.current,total=Math.max(1,(mission.decisions||[]).length),score=Math.max(0,Math.round((total-r.wrong.length)/total*100)),next={...r,completed:true};runtimeRef.current=next;setRuntime(next);await save(next,true,score);setOverlay({type:'complete',score})}
  function primary(){const r=runtimeRef.current,s=stages.find((x:any)=>x.id===r.stageId),o=currentObjective(r);if(o?.type==='actor'||o?.type==='object'){const n=nearRef.current;if(n&&n.type===o.type&&n.id===o.target)interactNear();return}if(o?.type==='decision'){const d=getDecision(o.target);if(decisionReady(d,r))setOverlay({type:'decision',d});return}if(o?.type==='advance'){const i=stages.findIndex((x:any)=>x.id===s?.id),next=stages[i+1];if(next)setOverlay({type:'transition',next:next.id,data:s?.transition||{}});return}if(!o&&s?.final)void finish()}
  function goStage(id:string){const next={...runtimeRef.current,stageId:id};apply(next);setOverlay(null);sceneRef.current?.buildStage?.(stages.find((s:any)=>s.id===id))}

  const nearIsTarget=!!(objective&&(objective.type==='actor'||objective.type==='object')&&near&&near.type===objective.type&&near.id===objective.target);
  const decisionCanOpen=objective?.type==='decision'?decisionReady(getDecision(objective.target),runtime):false;
  const primaryEnabled=ready&&(nearIsTarget||(objective?.type==='decision'&&decisionCanOpen)||objective?.type==='advance'||(!objective&&stage?.final));
  const targetName=targetEntity?.name||objective?.title||'';
  const guidance=!ready?'Preparando cenário':objective?.type==='actor'?(nearIsTarget?`Fale com ${targetName}`:`Vá até ${targetName}`):objective?.type==='object'?(nearIsTarget?(targetEntity?.interaction_text||`Examine ${targetName}`):`Vá até ${targetName}`):objective?.type==='decision'?(decisionCanOpen?objective.title:'Complete as evidências anteriores'):objective?.type==='advance'?(objective.title||'Avance para a próxima etapa'):(!objective&&stage?.final?'Concluir missão':'Explore o cenário');

  useEffect(()=>{let game:any,cancelled=false;(async()=>{try{const mod:any=await import('phaser');if(cancelled||!host.current)return;const P:any=mod.default||mod;
    class StudioScene extends P.Scene{
      player:any;actors:Record<string,any>={};objects:Record<string,any>={};cursors:any;keys:any;frozen=true;lastNear='';worldW=DESIGN_W;worldH=DESIGN_H;isDesktop=true;beacon:any;guide:any;focus:any;lastDistance=-1;
      constructor(){super('studio')}
      preload(){this.load.image('bg-parking',svgUri(sceneSvg('parking_night')));this.load.image('bg-station',svgUri(sceneSvg('police_station')));this.load.image('bg-court',svgUri(sceneSvg('courtroom')));for(const k of Object.keys(PALETTES))this.load.image(`char-${k}`,svgUri(chibiSvg(k)));this.load.image('char-player',svgUri(chibiSvg(character.archetype||'operational','player')));this.load.image('obj-camera',svgUri(objectSvg('camera')));this.load.image('obj-evidence',svgUri(objectSvg('evidence')));this.load.image('obj-document',svgUri(objectSvg('document')))}
      create(){sceneRef.current=this;this.cursors=this.input.keyboard?.createCursorKeys();this.keys=this.input.keyboard?.addKeys('W,A,S,D,SHIFT,E,ENTER');this.input.keyboard?.on('keydown-E',()=>{if(nearRef.current)interactNear();else primary()});this.input.keyboard?.on('keydown-ENTER',primary);this.buildStage(stages.find((x:any)=>x.id===runtimeRef.current.stageId)||stages[0]);this.scale.on('resize',()=>this.buildStage(stages.find((x:any)=>x.id===runtimeRef.current.stageId)||stages[0]));setReady(true);setCloud('Progresso salvo')}
      mapX(x:number){const p=Math.max(34,this.worldW*.025);return this.isDesktop?p+(x/DESIGN_W)*(this.worldW-p*2):x}
      mapY(y:number){const top=Math.max(84,this.worldH*.09),bottom=Math.max(86,this.worldH*.1);return this.isDesktop?top+(y/DESIGN_H)*(this.worldH-top-bottom):y}
      configure(){this.isDesktop=this.scale.width>=900;this.worldW=this.isDesktop?this.scale.width:DESIGN_W;this.worldH=this.isDesktop?this.scale.height:DESIGN_H;this.physics.world.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setZoom(this.isDesktop?1:Number(runtimeSettings?.settings?.camera_zoom_mobile||.86));if(this.isDesktop){this.cameras.main.stopFollow();this.cameras.main.setScroll(0,0)}}
      bgKey(s:any){return s.environment==='police_station'?'bg-station':s.environment==='courtroom'?'bg-court':'bg-parking'}
      nameplate(name:string,role:string,target=false){const c=this.add.container(0,0).setDepth(1200),w=Math.max(118,Math.min(210,name.length*8+38)),bg=this.add.rectangle(0,0,w,target?44:36,0x061820,target?.98:.9).setStrokeStyle(target?2:1,target?0x5de7ff:0x49636d,target?.95:.6),t=this.add.text(0,target?-7:-3,name,{fontFamily:'Inter,Arial',fontSize:target?'13px':'11px',fontStyle:'bold',color:'#fff'}).setOrigin(.5),r=this.add.text(0,10,role,{fontFamily:'Inter,Arial',fontSize:'8px',fontStyle:'bold',color:target?'#71e8ff':'#83b8c2'}).setOrigin(.5);c.add([bg,t,r]);return c}
      actor(def:any,isPlayer=false){const x=this.mapX(def.position?.x||600),y=this.mapY(def.position?.y||650),key=isPlayer?'char-player':`char-${def.visual?.archetype||def.style||'civilian'}`,img=this.physics.add.image(x,y,key).setOrigin(.5,.84);const scale=Math.max(.42,Math.min(.62,this.worldH/1600));img.setScale(scale);img.body.setSize(78,50);img.body.setOffset((img.width-78)/2,img.height*.7);img.body.setCollideWorldBounds(true);img.setDepth(y+20);(img as any).jqLabel=isPlayer?null:this.nameplate(def.name,def.role,false);return img}
      prop(def:any){const x=this.mapX(def.position?.x||500),y=this.mapY(def.position?.y||300),key=def.kind==='camera'?'obj-camera':def.kind==='evidence'?'obj-evidence':'obj-document',img=this.add.image(x,y,key).setScale(.55).setDepth(y+6);(img as any).jqLabel=this.nameplate(def.name||'Objeto',def.role||'EVIDÊNCIA',true);(img as any).jqLabel.setVisible(false);return img}
      questBeacon(){const c=this.add.container(0,0).setDepth(1400),halo=this.add.circle(0,0,25,0x55e6ff,.12).setStrokeStyle(3,0x68ecff,.9),diamond=this.add.rectangle(0,0,17,17,0x72edff).setRotation(Math.PI/4),stem=this.add.rectangle(0,28,4,50,0x72edff,.3).setOrigin(.5,1);c.add([stem,halo,diamond]);this.tweens.add({targets:halo,scale:1.6,alpha:.02,duration:850,yoyo:true,repeat:-1});this.tweens.add({targets:diamond,y:-9,duration:650,yoyo:true,repeat:-1,ease:'Sine.inOut'});return c}
      drawGuide(target:any){if(!this.guide)this.guide=this.add.graphics().setDepth(1250);this.guide.clear();if(!target||!this.player)return;const dx=target.x-this.player.x,dy=target.y-this.player.y,d=Math.hypot(dx,dy);if(d<115)return;const count=Math.min(10,Math.max(4,Math.floor(d/85)));for(let i=1;i<count;i++){const t=i/count,x=this.player.x+dx*t,y=this.player.y+dy*t;this.guide.fillStyle(0x68e8ff,.65*(1-t)+.2);this.guide.fillCircle(x,y,5+(i%2));}}
      buildStage(s:any){if(!s)return;this.children.removeAll(true);this.actors={};this.objects={};this.lastNear='';setNear(null);this.configure();const bg=this.add.image(this.worldW/2,this.worldH/2,this.bgKey(s)).setDisplaySize(this.worldW,this.worldH).setDepth(-100);bg.setAlpha(.98);const shade=this.add.rectangle(this.worldW/2,this.worldH/2,this.worldW,this.worldH,0x031017,s.environment==='parking_night'?.08:.02).setDepth(-90);shade.setBlendMode(P.BlendModes.MULTIPLY);this.player=this.actor({position:s.player_spawn||{x:600,y:650}},true);for(const a of s.actors||[])this.actors[a.id]={def:a,go:this.actor(a)};for(const o of s.objects||[])this.objects[o.id]={def:o,go:this.prop(o)};this.beacon=this.questBeacon();this.guide=this.add.graphics().setDepth(1240);if(!this.isDesktop)this.cameras.main.startFollow(this.player,true,.12,.12)}
      update(time:number){if(!this.player)return;const p:any=this.player,speed=this.keys?.SHIFT?.isDown?300:200,kx=((this.keys?.D?.isDown||this.cursors?.right?.isDown)?1:0)-((this.keys?.A?.isDown||this.cursors?.left?.isDown)?1:0),ky=((this.keys?.S?.isDown||this.cursors?.down?.isDown)?1:0)-((this.keys?.W?.isDown||this.cursors?.up?.isDown)?1:0),dx=kx+move.current.x,dy=ky+move.current.y,len=Math.hypot(dx,dy),moving=!this.frozen&&len>.05;if(moving){p.body.setVelocity(dx/len*speed,dy/len*speed);p.setFlipX(dx<-.05);p.angle=Math.sin(time/90)*1.4}else{p.body.setVelocity(0,0);p.angle=0}p.setDepth(p.y+20);const o=currentObjective(runtimeRef.current),targetId=o&&(o.type==='actor'||o.type==='object')?o.target:null,targetType=o?.type;let target:any=null;for(const[id,e]of Object.entries(this.actors)as any[]){e.go.setDepth(e.go.y+10);if(e.go.jqLabel){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-100;e.go.jqLabel.setAlpha(id===targetId?1:.68);e.go.jqLabel.setScale(id===targetId?1.05:.92)}if(targetType==='actor'&&id===targetId)target=e.go}for(const[id,e]of Object.entries(this.objects)as any[]){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-70;const isTarget=targetType==='object'&&id===targetId;e.go.jqLabel.setVisible(isTarget);if(isTarget)target=e.go}if(target&&this.beacon){this.beacon.setVisible(true);this.beacon.x=target.x;this.beacon.y=target.y-115+Math.sin(time/240)*4;this.drawGuide(target);const meters=Math.max(1,Math.round(P.Math.Distance.Between(p.x,p.y,target.x,target.y)/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.beacon?.setVisible(false);this.guide?.clear();if(this.lastDistance!==-1){this.lastDistance=-1;setDistance(null)}}let best:Near=null,bd=Number(runtimeSettings?.settings?.interaction_radius||120);for(const e of Object.values(this.actors)as any[]){const d=P.Math.Distance.Between(p.x,p.y,e.go.x,e.go.y);if(d<bd){bd=d;best={type:'actor',id:e.def.id,label:`Falar com ${e.def.name}`}}}for(const e of Object.values(this.objects)as any[]){const d=P.Math.Distance.Between(p.x,p.y,e.go.x,e.go.y);if(d<bd){bd=d;best={type:'object',id:e.def.id,label:e.def.interaction_text||`Examinar ${e.def.name}`}}}const key=best?`${best.type}:${best.id}`:'';if(key!==this.lastNear){this.lastNear=key;setNear(best)}}
    }
    game=new P.Game({type:P.AUTO,parent:host.current,width:window.innerWidth,height:window.innerHeight,transparent:true,physics:{default:'arcade',arcade:{debug:false}},scene:StudioScene,scale:{mode:P.Scale.RESIZE,autoCenter:P.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false,powerPreference:'high-performance'}})
  }catch(e:any){console.error(e);setEngineError(e?.message||'Falha ao iniciar o motor gráfico.');setCloud('Motor indisponível')}})();return()=>{cancelled=true;try{game?.destroy(true)}catch{}sceneRef.current=null}},[])
  useEffect(()=>{if(sceneRef.current)sceneRef.current.frozen=!!overlay||!!dialog||notebook||progressOpen||!runtime.started},[overlay,dialog,notebook,progressOpen,runtime.started]);

  const notes=runtime.facts.map(id=>stages.flatMap((s:any)=>[...(s.actors||[]),...(s.objects||[])]).find((x:any)=>x.fact?.id===id)?.fact).filter(Boolean),rules=runtime.decisions.map(id=>getDecision(id)).filter(Boolean),errors=runtime.wrong.map(id=>getDecision(id)).filter(Boolean);
  const stageObjectives=stage?.objectives||[];
  return <main className="studioGame"><div ref={host} className="studioCanvas"/><div className="studioHud"><header className="topMission"><div className="brand">JURIS<span>QUEST</span></div><div className="mission"><small>ETAPA {stageIndex+1} DE {stages.length}</small><strong>{mission.title}</strong><span>{stage?.location||stage?.title}</span></div></header><div className="topActions"><button onClick={()=>setNotebook(true)}><b>▤</b><span>Caderno</span><kbd>J</kbd></button><button onClick={()=>setProgressOpen(true)}><b>◫</b><span>Progresso</span><kbd>P</kbd></button><a href="/dashboard"><b>⚙</b><span>Menu</span><kbd>Esc</kbd></a></div><section className="objectiveCard"><div className="kicker"><i/> OBJETIVO ATUAL</div><h2>{objective?.title||'Etapa concluída'}</h2><p>{objective?.text||(stage?.final?'Finalize a missão.':'Avance para a próxima etapa.')}</p>{objective?.why&&<><button className="why" onClick={()=>setWhyOpen(v=>!v)}>› Por que isso importa?</button>{whyOpen&&<div className="whyText">{objective.why}</div>}</>}</section><section className="playerCard"><div className="avatarMini"><img src={svgUri(chibiSvg(character.archetype||'operational','player'))} alt=""/></div><div><b>{character.character_name||'Jogador'}</b><span>{character.role_title||'Candidato'}</span><div className="xp"><i/></div><small>Nvl. 1</small></div></section><section className="guideBar"><div className="guideIcon">!</div><div className="guideText"><b>{guidance}</b><span>{nearIsTarget?'Pressione E para interagir.':'Siga o marcador luminoso.'}</span></div>{distance&&<div className="distance">Distância: {distance} m</div>}{primaryEnabled&&<button onClick={primary}><kbd>E</kbd> Interagir</button>}</section><section className="keys"><div><kbd>W</kbd><kbd>S</kbd><kbd>D</kbd><span>Mover</span></div><div><kbd>E</kbd><span>Interagir</span></div><div><kbd>M</kbd><span>Mapa</span></div></section><div className={`sync ${cloud.includes('Falha')?'bad':''}`}>{cloud}</div></div>
  {engineError&&<ModalBox eyebrow="ERRO DO MOTOR" title="Não foi possível iniciar"><p>{engineError}</p><a className="mBtn" href="/dashboard">Voltar</a></ModalBox>}
  {overlay?.type==='brief'&&<ModalBox eyebrow={mission.briefing?.eyebrow||'MISSÃO INVESTIGATIVA'} title={mission.title} wide><p className="lead">{mission.briefing?.text||mission.summary}</p><div className="stats"><div><small>ETAPAS</small><b>{stages.length}</b></div><div><small>DECISÕES</small><b>{(mission.decisions||[]).length}</b></div><div><small>TEMPO</small><b>~{mission.estimated_minutes||15} min</b></div></div><div className="learning"><small>OBJETIVO DE APRENDIZAGEM</small><b>{mission.briefing?.learning_goal}</b></div><button className="mBtn primary" onClick={()=>{setOverlay(null);const next={...runtimeRef.current,started:true};runtimeRef.current=next;setRuntime(next);void save(next)}}>Entrar na ocorrência</button></ModalBox>}
  {dialog&&(()=>{const line=dialog.actor.dialogue?.[dialog.index]||{text:'Sem informação adicional.',choices:['Encerrar']};return <ModalBox eyebrow={dialog.actor.role} title={dialog.actor.name} wide><div className="dialog"><img src={svgUri(chibiSvg(dialog.actor.visual?.archetype||dialog.actor.style||'civilian'))} alt=""/><div><p>{line.text}</p><div className="choices">{(line.choices||['Continuar']).map((c:string,i:number)=><button key={i} onClick={()=>{if(dialog.index<(dialog.actor.dialogue?.length||1)-1)setDialog({...dialog,index:dialog.index+1});else{const f=dialog.actor.fact;setDialog(null);if(f)registerFact(f)}}}><span>{String.fromCharCode(65+i)}</span>{c}</button>)}</div><button className="close" onClick={()=>setDialog(null)}>Encerrar conversa</button></div></div></ModalBox>})()}
  {overlay?.type==='fact'&&<ModalBox eyebrow={overlay.fact.kind||'FATO REGISTRADO'} title={overlay.fact.title}><div className="infoCard"><p>{overlay.fact.text}</p></div><button className="mBtn primary" onClick={()=>setOverlay(null)}>Continuar</button></ModalBox>}
  {overlay?.type==='decision'&&<ModalBox eyebrow="DECISÃO JURÍDICA" title={overlay.d.title} wide><p className="question">{overlay.d.question}</p><div className="choices">{overlay.d.choices.map((c:any,i:number)=><button key={i} onClick={()=>void answer(overlay.d,i)}><span>{String.fromCharCode(65+i)}</span>{c.text}</button>)}</div></ModalBox>}
  {overlay?.type==='feedback'&&<ModalBox eyebrow={overlay.correct?'BOA ESCOLHA':'INFORMAÇÃO IMPORTANTE'} title={overlay.d.title} wide><div className={`feedback ${overlay.correct?'ok':'warn'}`}>{overlay.choice.feedback}</div><div className="feedbackGrid"><Info label="REGRA" text={overlay.d.feedback?.rule}/><Info label="APLICAÇÃO" text={overlay.d.feedback?.application}/><Info label="BASE LEGAL" text={overlay.d.feedback?.legal_basis}/><Info label="PEGADINHA" text={overlay.d.feedback?.trap}/><Info label="MEMÓRIA" text={overlay.d.feedback?.memory} wide/></div><button className="mBtn primary" onClick={()=>overlay.correct?setOverlay(null):setOverlay({type:'decision',d:overlay.d})}>{overlay.correct?'Consolidar e continuar':'Tentar novamente'}</button></ModalBox>}
  {overlay?.type==='transition'&&<ModalBox eyebrow={overlay.data.label||'TRANSIÇÃO'} title={overlay.data.title||'Próxima etapa'}><p>{overlay.data.text||'A missão avança.'}</p><button className="mBtn primary" onClick={()=>goStage(overlay.next)}>Seguir para a próxima cena</button></ModalBox>}
  {overlay?.type==='complete'&&<ModalBox eyebrow="MISSÃO CONCLUÍDA" title={mission.title} wide><p>{mission.review_plan?.completion_text}</p><div className="stats"><div><small>PROGRESSO</small><b>100%</b></div><div><small>1ª TENTATIVA</small><b>{overlay.score}%</b></div><div><small>ERROS</small><b>{runtime.wrong.length}</b></div></div><a className="mBtn primary" href="/dashboard">Voltar à campanha</a></ModalBox>}
  {notebook&&<ModalBox eyebrow="CADERNO" title="Fatos, regras e erros" wide><h3>Fatos coletados</h3>{notes.length?notes.map((f:any)=><Note key={f.id} title={f.title} text={f.text}/>):<p>Nenhum fato ainda.</p>}<h3>Regras consolidadas</h3>{rules.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.memory||d.feedback?.rule}/>)}<h3>Erros</h3>{errors.length?errors.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.trap}/>):<p>Nenhum erro de primeira tentativa.</p>}<button className="mBtn" onClick={()=>setNotebook(false)}>Fechar</button></ModalBox>}
  {progressOpen&&<ModalBox eyebrow={`ETAPA ${stageIndex+1} DE ${stages.length}`} title="Progresso da missão" wide><div className="progressList">{stageObjectives.map((o:any,i:number)=><div className={objectiveDone(o,runtime)?'done':o===objective?'current':''} key={`${o.type}-${o.target||i}`}><span>{objectiveDone(o,runtime)?'✓':i+1}</span><div><b>{o.title}</b><p>{o.text}</p></div></div>)}</div><button className="mBtn" onClick={()=>setProgressOpen(false)}>Fechar</button></ModalBox>}
  <style jsx global>{STUDIO_CSS}</style></main>
}

function ModalBox({eyebrow,title,children,wide=false}:{eyebrow:string;title:string;children?:any;wide?:boolean}){return <div className="modal"><section className={`sheet ${wide?'wide':''}`}><span className="ey">{eyebrow}</span><h2>{title}</h2>{children}</section></div>}
function Info({label,text,wide=false}:{label:string;text?:string;wide?:boolean}){if(!text)return null;return <div className={`info ${wide?'wide':''}`}><small>{label}</small><p>{text}</p></div>}
function Note({title,text}:{title:string;text:string;key?:any}){return <div className="note"><b>{title}</b><p>{text}</p></div>}
