'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { submitPlantaoAnswer } from '@/app/plantao/actions';
import { submitCampaignDecision } from '@/app/game/actions';
import { PALETTES as CHARACTERS, chibiSvg } from '@/lib/game/character-assets-v2';
import { directionalChibiSvg, type Facing } from '@/lib/game/character-directional-v3';
import { svgUri } from '@/lib/game/studio-assets';
import { objectSvg, sceneSvg } from '@/lib/game/scene-assets-v3';
import { STUDIO_CSS } from '@/lib/game/studio-css';
import { resolveVisualConfig } from '@/lib/game/visual-contract';

type RuntimeMode='campaign'|'patrol';
type PatrolContext={runId:string;itemId:string;sequence:number;total:number;prioritySource?:string};
type Props={
  missionId:string;
  mission:any;
  userId:string;
  initialCharacter?:any;
  initialProgress?:any;
  runtimeSettings?:any;
  visualPresets?:any[];
  replayMode?:boolean;
  exploreMode?:boolean;
  exploreStage?:string|null;
  mode?:RuntimeMode;
  patrolContext?:PatrolContext|null;
};
type Runtime={stageId:string;facts:string[];decisions:string[];wrong:string[];attemptCounts:Record<string,number>;started:boolean;completed:boolean};
type Near={type:'actor'|'object';id:string}|null;
type PatrolResult={correct:boolean;answered_count:number;correct_count:number;item_count:number;complete:boolean;xp:number;feedback?:any};
type FeedbackOverlay={type:'feedback';d:any;choice:any;choiceIndex:number;correct:boolean;next:Runtime;saved:boolean;saveError?:boolean;patrolResult?:PatrolResult};
type Overlay=null|{type:'brief'}|{type:'fact';fact:any;next:any;explore?:boolean}|{type:'decision';d:any}|FeedbackOverlay|{type:'decisionError';d:any;message:string}|{type:'transition';next:string;data:any}|{type:'complete';score:number};

const DW=1200,DH=760;
const WALK_SPEED=105;
const MANUAL_SPEED=125;

const EXTRA_CSS=`
.scenePicker{display:grid;gap:9px}.scenePicker button{display:grid;grid-template-columns:42px 1fr auto;gap:11px;align-items:center;text-align:left;padding:12px;border:1px solid #31586b;border-radius:12px;background:#09232e;color:#eef5f5;cursor:pointer}.scenePicker button:hover{border-color:#70ddeb;background:#0b2d3b}.scenePicker button.active{border-color:#e2bd59;background:#292416}.scenePicker .num{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:#113844;color:#e9c95f;font-weight:900}.scenePicker small{color:#87a0a5}.decisionStatus{display:flex;gap:8px;align-items:center;margin:10px 0;padding:9px 11px;border-radius:10px;background:#071a24;border:1px solid #294e5d;color:#a8b9bd;font-size:11px}.decisionStatus.bad{border-color:#8f4e49;background:#291817;color:#f0b0aa}.choiceWrong{border-color:#a45954!important;background:#2d1918!important}.choiceCorrect{border-color:#4f936e!important;background:#0c2a1c!important}.exploreBadge{color:#82e6ce!important}.npcHint{font-size:9px;color:#86cbd6;margin-top:4px}
.targetBadge{display:flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;background:#e5bd58;color:#181309;font:900 8px ui-monospace;letter-spacing:.08em;box-shadow:0 0 26px #e5bd5880;pointer-events:none}.targetBadge:before{content:'●';font-size:7px}.clickHint{color:#e5c96c!important}.guideBar .guideText span{max-width:560px}.feedbackGrid{gap:10px!important}.feedbackGrid .info{padding:14px 15px!important;border-radius:12px!important;background:linear-gradient(180deg,#091d25,#06161c)!important;border:1px solid #31505a!important}.feedbackGrid .info small{font-size:8px!important;letter-spacing:.11em!important;color:#77d8e2!important}.feedbackGrid .info p{font-size:12px!important;line-height:1.62!important;color:#d3dedf!important;margin-top:7px!important}.feedbackGrid .info.wide{border-color:#705f37!important;background:linear-gradient(180deg,#201c10,#12150f)!important}.feedback{padding:15px 16px!important;border-radius:13px!important}.feedback b{font-size:14px!important}.feedback p{font-size:12px!important;line-height:1.55!important}.patrolStrip{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0 0}.patrolStrip span{padding:5px 8px;border-radius:999px;border:1px solid #45606a;background:#07191f;color:#9db2b6;font:800 8px ui-monospace}.patrolStrip span.priority{border-color:#705f37;color:#ebc861;background:#211c0f}.topMission .mission .modeLine{color:#e5c15d!important}.studioHud .keys{opacity:.36!important;transition:opacity .2s}.studioHud .keys:hover{opacity:1!important}
`;
const ALL_CSS=STUDIO_CSS+EXTRA_CSS;

export default function GameRuntimeProV4({missionId,mission,userId,initialCharacter,initialProgress,runtimeSettings,visualPresets=[],replayMode=false,exploreMode=false,exploreStage=null,mode='campaign',patrolContext=null}:Props){
  const router=useRouter();
  const isPatrol=mode==='patrol';
  const stages=useMemo(()=>[...(mission.stages||[])].sort((a:any,b:any)=>(a.order||0)-(b.order||0)),[mission]);
  const validExploreStage=exploreMode&&stages.some((s:any)=>s.id===exploreStage)?exploreStage:null;
  const storedReplay=initialProgress?.runtime_state?.replay;
  const replayResume=replayMode&&storedReplay&&!storedReplay.completed?storedReplay:null;
  const baseResume=initialProgress?.runtime_state||{};
  const resume=replayMode?(replayResume||{}):baseResume;
  const freshReplay=replayMode&&!replayResume;
  const initial:Runtime=isPatrol
    ?{stageId:stages[0]?.id||'',facts:[],decisions:[],wrong:[],attemptCounts:{},started:false,completed:false}
    :exploreMode
      ?{stageId:validExploreStage||stages[0]?.id||'',facts:initialProgress?.facts||[],decisions:Object.keys(initialProgress?.decisions||{}),wrong:initialProgress?.mistakes||[],attemptCounts:initialProgress?.decisions||{},started:true,completed:false}
      :freshReplay
        ?{stageId:stages[0]?.id||'',facts:[],decisions:[],wrong:[],attemptCounts:{},started:false,completed:false}
        :{stageId:resume.stageId||initialProgress?.current_stage||stages[0]?.id||'',facts:resume.facts||initialProgress?.facts||[],decisions:resume.decisions||[],wrong:resume.wrong||initialProgress?.mistakes||[],attemptCounts:resume.attemptCounts||initialProgress?.decisions||{},started:resume.started??!!initialProgress,completed:replayMode?!!resume.completed:initialProgress?.status==='completed'};
  const initialOverlay:Overlay=exploreMode?null:initial.completed?{type:'complete',score:Number(replayMode?initialProgress?.runtime_state?.replay_score:initialProgress?.score_best||initialProgress?.score_first_try||100)}:initial.started?null:{type:'brief'};
  const [runtime,setRuntime]=useState(initial); const rr=useRef(initial);
  const [near,setNear]=useState<Near>(null); const nr=useRef<Near>(null);
  const [overlay,setOverlay]=useState<Overlay>(initialOverlay);
  const [dialog,setDialog]=useState<any>(null); const [notebook,setNotebook]=useState(false); const [progressOpen,setProgressOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false); const [scenePicker,setScenePicker]=useState(false); const [whyOpen,setWhyOpen]=useState(false); const [decisionBusy,setDecisionBusy]=useState(false);
  const [ready,setReady]=useState(false); const [cloud,setCloud]=useState(exploreMode?'Exploração livre':isPatrol?'Plantão pronto':'Sincronizando…'); const [engineError,setEngineError]=useState(''); const [distance,setDistance]=useState<number|null>(null);
  const host=useRef<HTMLDivElement>(null); const sceneRef=useRef<any>(null); const sb=useRef(createClient()); const saveChain=useRef<Promise<boolean>>(Promise.resolve(true));
  const blockedRef=useRef(false); const primaryRef=useRef<()=>void>(()=>{});
  const character=initialCharacter||{character_name:'Jogador',role_title:'Candidato',archetype:'operational'};
  const stage=stages.find((s:any)=>s.id===runtime.stageId)||stages[0]; const stageIndex=Math.max(0,stages.findIndex((s:any)=>s.id===stage?.id));
  useEffect(()=>{rr.current=runtime},[runtime]); useEffect(()=>{nr.current=near},[near]);

  function entityForObjective(o:any,r=rr.current){const s=stages.find((x:any)=>x.id===r.stageId);if(!s||!o)return null;if(o.type==='actor')return(s.actors||[]).find((x:any)=>x.id===o.target)||null;if(o.type==='object')return(s.objects||[]).find((x:any)=>x.id===o.target)||null;return null}
  function factIdForObjective(o:any,r=rr.current){return entityForObjective(o,r)?.fact?.id||o?.target}
  const hasFact=(id:string,r=rr.current)=>r.facts.includes(id),hasDecision=(id:string,r=rr.current)=>r.decisions.includes(id),getDecision=(id:string)=>(mission.decisions||[]).find((d:any)=>d.id===id);
  function objectiveDone(o:any,r=rr.current){if(!o)return false;if(o.type==='actor'||o.type==='object')return hasFact(factIdForObjective(o,r),r);if(o.type==='decision')return hasDecision(o.target,r);return false}
  function currentObjective(r=rr.current){if(exploreMode)return null;const s=stages.find((x:any)=>x.id===r.stageId);return(s?.objectives||[]).find((o:any)=>o.type==='advance'||!objectiveDone(o,r))||null}
  function decisionReady(d:any,r=rr.current){return!!d&&(d.requires_facts||[]).every((f:string)=>hasFact(f,r))&&(d.depends_on||[]).every((x:string)=>hasDecision(x,r))}
  function overallProgress(r=rr.current){const os=stages.flatMap((s:any)=>(s.objectives||[]).filter((o:any)=>o.type!=='advance'));return os.length?Math.round(os.filter((o:any)=>objectiveDone(o,r)).length/os.length*100):0}
  function nextObjectiveLabel(r:Runtime){const o=currentObjective(r);if(!o)return isPatrol?'Ocorrência pronta para decisão':'Etapa concluída';const e=entityForObjective(o,r);if(o.type==='actor')return`Fale com ${e?.name||o.title}`;if(o.type==='object')return e?.interaction_text||`Examine ${e?.name||o.title}`;return o.title}
  function specificDistractor(d:any,index:number){const wrongIndexes=(d?.choices||[]).map((c:any,i:number)=>!c.correct?i:-1).filter((i:number)=>i>=0);const pos=wrongIndexes.indexOf(index);return pos>=0?d?.feedback?.distractors?.[pos]:null}

  function replayPayload(next:Runtime,complete=false,score:number|null=null){const root={...(initialProgress?.runtime_state||{})};return{user_id:userId,mission_id:missionId,status:initialProgress?.status||'completed',current_stage:initialProgress?.current_stage||stages.at(-1)?.id||next.stageId,progress_percent:Number(initialProgress?.progress_percent??100),score_first_try:initialProgress?.score_first_try??null,score_best:complete?Math.max(Number(initialProgress?.score_best||0),Number(score||0)):initialProgress?.score_best??null,mistakes:initialProgress?.mistakes||[],facts:initialProgress?.facts||[],decisions:initialProgress?.decisions||{},runtime_state:{...root,replay:next,replay_updated_at:new Date().toISOString(),...(complete?{replay_score:score}:{})},started_at:initialProgress?.started_at||new Date().toISOString(),completed_at:initialProgress?.completed_at||new Date().toISOString(),updated_at:new Date().toISOString()}}
  function normalPayload(next:Runtime,complete=false,score:number|null=null){return{user_id:userId,mission_id:missionId,status:complete?'completed':'in_progress',current_stage:next.stageId,progress_percent:complete?100:overallProgress(next),score_first_try:complete?score:null,score_best:complete?score:null,mistakes:next.wrong,facts:next.facts,decisions:next.attemptCounts,runtime_state:next,started_at:initialProgress?.started_at||new Date().toISOString(),completed_at:complete?new Date().toISOString():null,updated_at:new Date().toISOString()}}
  function persist(next:Runtime,complete=false,score:number|null=null){
    if(exploreMode||isPatrol)return Promise.resolve(true);
    saveChain.current=saveChain.current.then(async()=>{setCloud(replayMode?'Salvando repetição…':'Salvando…');const payload=replayMode?replayPayload(next,complete,score):normalPayload(next,complete,score);const{error}=await sb.current.from('mission_progress').upsert(payload,{onConflict:'user_id,mission_id'});if(error){console.error('mission save failed',error);setCloud('Falha ao salvar');return false}setCloud(replayMode?'Repetição salva':'Progresso salvo');return true}).catch(e=>{console.error(e);setCloud('Falha ao salvar');return false});return saveChain.current
  }
  function setLocal(next:Runtime){rr.current=next;setRuntime(next)}
  async function registerFact(f:any){if(!f?.id)return false;if(exploreMode){setDialog(null);setOverlay({type:'fact',fact:f,next:null,explore:true});return true}if(hasFact(f.id)){setDialog(null);return true}const next={...rr.current,facts:[...rr.current.facts,f.id]};const ok=await persist(next);if(!ok)return false;setLocal(next);setDialog(null);setOverlay({type:'fact',fact:f,next:currentObjective(next)});return true}
  async function saveFeedbackState(fb:FeedbackOverlay){if(isPatrol)return true;const ok=await persist(fb.next);setOverlay({...fb,saved:ok,saveError:!ok});return ok}
  async function answer(d:any,i:number){
    if(decisionBusy)return;const c=d?.choices?.[i];if(!c)return;setDecisionBusy(true);setCloud('Registrando decisão…');
    try{
      const r=rr.current,runAttempt=(r.attemptCounts[d.id]||0)+1;
      if(isPatrol){
        if(!patrolContext){setOverlay({type:'decisionError',d,message:'Contexto do Plantão indisponível.'});return}
        const response=await submitPlantaoAnswer({runId:patrolContext.runId,itemId:patrolContext.itemId,index:i});
        if(!response.ok){setOverlay({type:'decisionError',d,message:response.error||'Não foi possível registrar a decisão.'});setCloud('Falha ao registrar');return}
        const pr=response.data as PatrolResult;
        const correct=!!pr.correct;
        const wrong=!correct&&!r.wrong.includes(d.id)?[...r.wrong,d.id]:r.wrong;
        const next={...r,wrong,attemptCounts:{...r.attemptCounts,[d.id]:runAttempt},decisions:r.decisions.includes(d.id)?r.decisions:[...r.decisions,d.id]};
        setLocal(next);
        const mergedDecision={...d,feedback:{...(d.feedback||{}),...(pr.feedback||{})}};
        setOverlay({type:'feedback',d:mergedDecision,choice:c,choiceIndex:i,correct,next,saved:true,patrolResult:pr});
        setCloud(correct?'Decisão registrada':'Erro enviado para recuperação');
        return;
      }
      const response=await submitCampaignDecision({missionId,decisionId:d.id,index:i,mode:replayMode?'replay':'mission'});
      if(!response.ok||!response.data){setOverlay({type:'decisionError',d,message:response.error||'A tentativa não foi registrada. Nada foi perdido; clique para tentar novamente.'});setCloud('Falha ao registrar tentativa');return}
      const server=response.data,actualAttempt=Number(server.attemptNo||runAttempt),correct=!!server.correct,wrong=!correct&&actualAttempt===1&&!r.wrong.includes(d.id)?[...r.wrong,d.id]:r.wrong,base={...r,wrong,attemptCounts:{...r.attemptCounts,[d.id]:actualAttempt}},next=correct?{...base,decisions:base.decisions.includes(d.id)?base.decisions:[...base.decisions,d.id]}:base;
      const serverDecision={...d,feedback:server.feedback||{}},serverChoice={...c,text:server.selectedText||c.text,feedback:server.feedback?.choice_feedback};
      setLocal(next);const fb:FeedbackOverlay={type:'feedback',d:serverDecision,choice:serverChoice,choiceIndex:i,correct,next,saved:false};setOverlay(fb);setCloud(correct?'Resposta registrada • salvando…':'Erro registrado • salvando…');await saveFeedbackState(fb)
    }finally{setDecisionBusy(false)}
  }
  async function finish(){if(isPatrol){router.refresh();return}const r=rr.current,total=Math.max(1,(mission.decisions||[]).length),score=Math.max(0,Math.round((total-r.wrong.length)/total*100)),next={...r,completed:true};const ok=await persist(next,true,score);if(!ok)return;setLocal(next);setOverlay({type:'complete',score})}
  async function goStage(id:string){const next={...rr.current,stageId:id};if(exploreMode){setLocal(next);setOverlay(null);setScenePicker(false);sceneRef.current?.buildStage?.(stages.find((s:any)=>s.id===id));return}const ok=await persist(next);if(!ok)return;setLocal(next);setOverlay(null);sceneRef.current?.buildStage?.(stages.find((s:any)=>s.id===id))}
  function primary(){const r=rr.current;if(exploreMode){const n=nr.current,s=stages.find((x:any)=>x.id===r.stageId);if(!n||!s)return;if(n.type==='actor'){const a=(s.actors||[]).find((x:any)=>x.id===n.id);if(a)setDialog({actor:a,index:0,explore:true})}else{const o=(s.objects||[]).find((x:any)=>x.id===n.id);if(o?.fact)setOverlay({type:'fact',fact:o.fact,next:null,explore:true})}return}const o=currentObjective(r);if(o?.type==='actor'||o?.type==='object'){const n=nr.current;if(n&&n.type===o.type&&n.id===o.target){const s=stages.find((x:any)=>x.id===r.stageId);if(o.type==='actor'){const a=(s?.actors||[]).find((x:any)=>x.id===o.target);if(a)setDialog({actor:a,index:0})}else{const obj=(s?.objects||[]).find((x:any)=>x.id===o.target);if(obj?.fact)void registerFact(obj.fact)}}return}if(o?.type==='decision'){const d=getDecision(o.target);if(decisionReady(d,r))setOverlay({type:'decision',d});return}if(o?.type==='advance'){const i=stages.findIndex((x:any)=>x.id===r.stageId),next=stages[i+1];if(next)setOverlay({type:'transition',next:next.id,data:stages[i]?.transition||{}});return}const s=stages.find((x:any)=>x.id===r.stageId);if(!o&&s?.final)void finish()}
  primaryRef.current=primary;

  const objective=currentObjective(runtime),target=entityForObjective(objective,runtime),nearIsTarget=!!(objective&&(objective.type==='actor'||objective.type==='object')&&near&&near.type===objective.type&&near.id===objective.target),decisionCanOpen=objective?.type==='decision'?decisionReady(getDecision(objective.target),runtime):false;
  const primaryEnabled=ready&&(exploreMode?!!near:(nearIsTarget||(objective?.type==='decision'&&decisionCanOpen)||objective?.type==='advance'||(!objective&&stage?.final)));
  const guidance=exploreMode?near?`Interaja com ${near.type==='actor'?'o personagem':'a evidência'}`:'Explore livremente o cenário':!ready?'Preparando cenário':objective?.type==='actor'?(nearIsTarget?`Fale com ${target?.name||objective.title}`:`Clique em ${target?.name||objective.title}`):objective?.type==='object'?(nearIsTarget?(target?.interaction_text||`Examine ${target?.name||objective.title}`):`Clique em ${target?.name||objective.title}`):objective?.type==='decision'?(decisionCanOpen?objective.title:'Complete as evidências anteriores'):objective?.type==='advance'?(objective.title||'Avance para a próxima etapa'):(!objective&&stage?.final?(isPatrol?'Encerrar ocorrência':'Concluir missão'):'Explore o cenário');
  useEffect(()=>{setWhyOpen(false)},[runtime.stageId,objective?.target,objective?.type]);
  useEffect(()=>{blockedRef.current=!!overlay||!!dialog||notebook||progressOpen||menuOpen||scenePicker||!runtime.started},[overlay,dialog,notebook,progressOpen,menuOpen,scenePicker,runtime.started]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.repeat)return;const k=e.key.toLowerCase();if(k==='j'&&!overlay&&!dialog){setNotebook(v=>!v);setProgressOpen(false);setMenuOpen(false);setScenePicker(false)}else if(k==='p'&&!overlay&&!dialog&&!exploreMode){setProgressOpen(v=>!v);setNotebook(false);setMenuOpen(false)}else if(k==='c'&&exploreMode&&!overlay&&!dialog){setScenePicker(v=>!v);setNotebook(false);setMenuOpen(false)}else if(e.key==='Escape'){if(notebook)setNotebook(false);else if(progressOpen)setProgressOpen(false);else if(scenePicker)setScenePicker(false);else if(menuOpen)setMenuOpen(false);else if(dialog)setDialog(null);else if(!overlay)setMenuOpen(true)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[overlay,dialog,notebook,progressOpen,menuOpen,scenePicker,exploreMode]);

  useEffect(()=>{let game:any,cancelled=false;(async()=>{try{const mod:any=await import('phaser');if(cancelled||!host.current)return;const P:any=mod.default||mod;class Scene extends P.Scene{
    player:any;actors:Record<string,any>={};objects:Record<string,any>={};keys:any;cursors:any;worldW=DW;worldH=DH;isDesktop=true;beacon:any;guide:any;targetBadge:any;lastNear='';lastDistance=-1;rain:any[]=[];dust:any[]=[];autoTarget:any=null;autoOpenLock=false;
    constructor(){super('pro-v4')}
    preload(){this.load.image('bg-parking',svgUri(sceneSvg('parking_night')));this.load.image('bg-station',svgUri(sceneSvg('police_station')));this.load.image('bg-court',svgUri(sceneSvg('courtroom')));for(const k of Object.keys(CHARACTERS)){for(const f of ['front','back','side'] as Facing[])this.load.image(`char-${k}-${f}`,svgUri(directionalChibiSvg(k,f)))}for(const f of ['front','back','side'] as Facing[])this.load.image(`char-player-${f}`,svgUri(directionalChibiSvg(character.archetype||'operational',f,'player')));this.load.image('obj-camera',svgUri(objectSvg('camera')));this.load.image('obj-evidence',svgUri(objectSvg('evidence')));this.load.image('obj-document',svgUri(objectSvg('document')))}
    create(){sceneRef.current=this;this.cursors=this.input.keyboard?.createCursorKeys();this.keys=this.input.keyboard?.addKeys('W,A,S,D,E,ENTER');this.input.keyboard?.on('keydown-E',()=>primaryRef.current());this.input.keyboard?.on('keydown-ENTER',()=>primaryRef.current());this.buildStage(stages.find((x:any)=>x.id===rr.current.stageId)||stages[0]);this.scale.on('resize',()=>this.buildStage(stages.find((x:any)=>x.id===rr.current.stageId)||stages[0]));setReady(true);setCloud(exploreMode?'Exploração livre':isPatrol?'Plantão pronto':replayMode?'Modo repetição':'Progresso salvo')}
    mapX(x:number){const p=Math.max(34,this.worldW*.025);return p+(x/DW)*(this.worldW-p*2)} mapY(y:number){const t=Math.max(84,this.worldH*.09),b=Math.max(86,this.worldH*.1);return t+(y/DH)*(this.worldH-t-b)}
    visual(s:any){return resolveVisualConfig(s,mission,visualPresets,runtimeSettings||undefined)}
    configure(s:any){this.isDesktop=this.scale.width>=900;this.worldW=this.isDesktop?this.scale.width:DW;this.worldH=this.isDesktop?this.scale.height:DH;this.physics.world.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBounds(0,0,this.worldW,this.worldH);const v=this.visual(s),desktopZoom=Math.max(.94,Math.min(1.06,Number(v?.camera_zoom||1)));this.cameras.main.setZoom(this.isDesktop?desktopZoom:Number(runtimeSettings?.settings?.camera_zoom_mobile||.86));if(this.isDesktop){this.cameras.main.stopFollow();this.cameras.main.setScroll(0,0)}}
    bgKey(s:any){return s.environment==='police_station'?'bg-station':s.environment==='courtroom'?'bg-court':'bg-parking'}
    label(name:string,role:string){const c=this.add.container(0,0).setDepth(1600),w=Math.max(132,Math.min(220,name.length*9+48)),bg=this.add.rectangle(0,0,w,44,0x020d12,.94).setStrokeStyle(2,0x79dbe8,.78),t=this.add.text(0,-7,name,{fontFamily:'Inter,Arial',fontSize:'14px',fontStyle:'bold',color:'#ffffff',stroke:'#001015',strokeThickness:3}).setOrigin(.5),r=this.add.text(0,10,String(role||'NPC').toUpperCase(),{fontFamily:'Inter,Arial',fontSize:'9px',fontStyle:'bold',color:'#8de4ee',letterSpacing:1}).setOrigin(.5);c.add([bg,t,r]);(c as any).jqBg=bg;return c}
    setFacing(img:any,style:string,facing:Facing,flip=false,isPlayer=false){const key=isPlayer?`char-player-${facing}`:`char-${style}-${facing}`;if(img.texture?.key!==key)img.setTexture(key);img.setFlipX(facing==='side'&&flip)}
    canClick(type:'actor'|'object',id:string){if(blockedRef.current)return false;if(exploreMode)return true;const o=currentObjective(rr.current);return!!o&&o.type===type&&o.target===id}
    startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;const d=Math.hypot(go.x-this.player.x,go.y-this.player.y);const speed=Math.max(90,Math.min(155,d/7));this.autoTarget={type,id,go,speed,jqDistanceAwareWalk:true};this.autoOpenLock=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`)}
    actor(def:any,isPlayer=false){const x=this.mapX(def.position?.x||600),y=this.mapY(def.position?.y||650),style=def.visual?.archetype||def.style||'civilian',facing=(def.visual?.facing||'front') as Facing,img=this.physics.add.image(x,y,isPlayer?`char-player-${facing}`:`char-${style}-${facing}`).setOrigin(.5,.84),scale=Math.max(.4,Math.min(.6,this.worldH/1580));img.setScale(scale);(img as any).jqBaseScale=scale;img.body.setSize(74,46);img.body.setCollideWorldBounds(true);img.setDepth(y+20);(img as any).jqLabel=isPlayer?null:this.label(def.name,def.role);(img as any).jqStyle=style;(img as any).jqDefaultFacing=facing;if(!isPlayer){img.setInteractive({useHandCursor:true});img.on('pointerdown',()=>this.startAuto('actor',def.id,img));const hit=this.add.zone(x,y-Math.max(18,img.displayHeight*.18),Math.max(118,img.displayWidth*1.55),Math.max(132,img.displayHeight*.92)).setDepth(y+22).setInteractive({useHandCursor:true});(hit as any).jqInteractionHit=true;hit.on('pointerdown',()=>this.startAuto('actor',def.id,img));(img as any).jqHit=hit}return img}
    prop(def:any){const x=this.mapX(def.position?.x||500),y=this.mapY(def.position?.y||300),key=def.kind==='camera'?'obj-camera':def.kind==='evidence'?'obj-evidence':'obj-document',img=this.add.image(x,y,key).setScale(.5).setDepth(y+6);(img as any).jqLabel=this.label(def.name||'Objeto',def.role||'EVIDÊNCIA');(img as any).jqLabel.setVisible(false);img.setInteractive({useHandCursor:true});img.on('pointerdown',()=>this.startAuto('object',def.id,img));const hit=this.add.zone(x,y,132,132).setDepth(y+9).setInteractive({useHandCursor:true});(hit as any).jqInteractionHit=true;hit.on('pointerdown',()=>this.startAuto('object',def.id,img));(img as any).jqHit=hit;return img}
    ambient(s:any){const v=this.visual(s),quality=this.isDesktop?(runtimeSettings?.renderer_quality||'high'):(runtimeSettings?.mobile_quality||'balanced'),rich=v?.density==='rich',low=quality==='low';const time=v?.time||'day',weather=v?.weather||'clear',particles=v?.particles||'none',fog=Math.max(0,Math.min(.35,Number(v?.fog||0))),vignette=Math.max(0,Math.min(.4,Number(v?.vignette||0)));let tint=0x88dbe8,alpha=.018;if(time==='night'){tint=0x1d5d78;alpha=.095}else if(time==='sunset'){tint=0xf0a050;alpha=.105}else if(time==='day'){tint=0xd9f2ef;alpha=.035}else if(time==='indoor'){tint=s.environment==='courtroom'?0xffdfaa:0xbceff0;alpha=.028}const wash=this.add.rectangle(this.worldW/2,this.worldH/2,this.worldW,this.worldH,tint,alpha).setDepth(-78);wash.setBlendMode(time==='night'?P.BlendModes.MULTIPLY:P.BlendModes.ADD);if(s.environment==='parking_night'||time==='night'){for(const x of [180,520,1080,1430]){const light=this.add.circle(x/1600*this.worldW,155/900*this.worldH,Math.max(75,this.worldH*.11),0xffd77d,rich?.055:.038).setDepth(-70);light.setBlendMode(P.BlendModes.ADD)}}if(fog>0&&!low){const n=rich?5:3;for(let i=0;i<n;i++){const f=this.add.ellipse((i+.35)/n*this.worldW,this.worldH*(.28+(i%2)*.22),this.worldW*.42,this.worldH*.28,0xc5edf2,fog*.16).setDepth(35);f.setBlendMode(P.BlendModes.SCREEN);this.tweens.add({targets:f,x:f.x+(i%2?70:-70),alpha:{from:f.alpha*.7,to:f.alpha},duration:6500+i*900,yoyo:true,repeat:-1,ease:'Sine.easeInOut'})}}const rainOn=weather==='rain'||particles==='rain';if(rainOn&&!low){const count=rich?56:quality==='high'?42:28;for(let i=0;i<count;i++){const line=this.add.rectangle(Math.random()*this.worldW,Math.random()*this.worldH,1,12+Math.random()*11,0xb7ecff,.10+Math.random()*.08).setRotation(-.16).setDepth(40);this.rain.push(line)}}const dustOn=particles==='dust'&&weather!=='rain';if(dustOn&&!low){const count=rich?20:12;for(let i=0;i<count;i++){const d=this.add.circle(Math.random()*this.worldW,Math.random()*this.worldH,1+Math.random()*1.6,0xffe4aa,.08+Math.random()*.10).setDepth(34);this.dust.push(d);this.tweens.add({targets:d,y:d.y-24-Math.random()*42,x:d.x-12+Math.random()*24,alpha:{from:d.alpha*.35,to:d.alpha},duration:4200+Math.random()*4200,yoyo:true,repeat:-1,ease:'Sine.easeInOut'})}}if(weather==='overcast'){this.add.rectangle(this.worldW/2,this.worldH/2,this.worldW,this.worldH,0x8aa1a7,.07).setDepth(30).setBlendMode(P.BlendModes.MULTIPLY)}if(vignette>0){const a=vignette*.33,th=Math.max(55,this.worldH*.11);this.add.rectangle(this.worldW/2,th/2,this.worldW,th,0x000000,a).setDepth(1500);this.add.rectangle(this.worldW/2,this.worldH-th/2,this.worldW,th,0x000000,a).setDepth(1500);this.add.rectangle(th/2,this.worldH/2,th,this.worldH,0x000000,a*.65).setDepth(1500);this.add.rectangle(this.worldW-th/2,this.worldH/2,th,this.worldH,0x000000,a*.65).setDepth(1500)}}
    buildStage(s:any){if(!s)return;this.children.removeAll(true);this.rain=[];this.dust=[];this.actors={};this.objects={};this.lastNear='';this.autoTarget=null;setNear(null);setDistance(null);this.configure(s);this.add.image(this.worldW/2,this.worldH/2,this.bgKey(s)).setDisplaySize(this.worldW,this.worldH).setDepth(-100);this.ambient(s);this.player=this.actor({position:s.player_spawn||{x:600,y:650},visual:{facing:'front'}},true);for(const a of s.actors||[])this.actors[a.id]={def:a,go:this.actor(a)};for(const o of s.objects||[])this.objects[o.id]={def:o,go:this.prop(o)};this.beacon=this.add.circle(0,0,22,0x55e6ff,.1).setStrokeStyle(3,0xe7c15c,.96).setDepth(1700);this.guide=this.add.graphics().setDepth(1240);this.targetBadge=this.add.text(0,0,'PRÓXIMO PASSO • CLIQUE',{fontFamily:'Inter,Arial',fontSize:'10px',fontStyle:'bold',color:'#171309',backgroundColor:'#e5bd58',padding:{x:9,y:5}}).setOrigin(.5).setDepth(1800).setVisible(false);if(!this.isDesktop)this.cameras.main.startFollow(this.player,true,.12,.12)}
    nearestExplore(){let best:any=null,bestD=Infinity;for(const[id,e]of Object.entries(this.actors)as any[]){const d=P.Math.Distance.Between(this.player.x,this.player.y,e.go.x,e.go.y);if(d<bestD){bestD=d;best={type:'actor',id,go:e.go}}}for(const[id,e]of Object.entries(this.objects)as any[]){const d=P.Math.Distance.Between(this.player.x,this.player.y,e.go.x,e.go.y);if(d<bestD){bestD=d;best={type:'object',id,go:e.go}}}return best&&bestD<Number(runtimeSettings?.settings?.interaction_radius||125)?{...best,d:bestD}:null}
    faceMove(dx:number,dy:number,time:number){const f:Facing=Math.abs(dy)>=Math.abs(dx)?(dy<0?'back':'front'):'side';this.setFacing(this.player,character.archetype||'operational',f,dx<0,true);const base=Number(this.player.jqBaseScale||this.player.scaleX||.5),step=Math.sin(time/82),lift=Math.abs(step);this.player.angle=step*1.05;this.player.setScale(base*(1+lift*.018),base*(1-lift*.028));}
    update(time:number){
      if(!this.player)return;for(const r of this.rain){r.y+=3.4;if(r.y>this.worldH){r.y=-20;r.x=Math.random()*this.worldW}}for(const d of this.dust){if(d.y<-10)d.y=this.worldH+10}
      const kx=((this.keys?.D?.isDown||this.cursors?.right?.isDown)?1:0)-((this.keys?.A?.isDown||this.cursors?.left?.isDown)?1:0),ky=((this.keys?.S?.isDown||this.cursors?.down?.isDown)?1:0)-((this.keys?.W?.isDown||this.cursors?.up?.isDown)?1:0),len=Math.hypot(kx,ky);
      if(!blockedRef.current&&len>.05){this.autoTarget=null;this.player.body.setVelocity(kx/len*MANUAL_SPEED,ky/len*MANUAL_SPEED);this.faceMove(kx,ky,time)}
      else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,dx=t.go.x-this.player.x,dy=t.go.y-this.player.y,d=Math.hypot(dx,dy),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78);if(d>radius){this.player.body.setVelocity(dx/d*(t.speed||WALK_SPEED),dy/d*(t.speed||WALK_SPEED));this.faceMove(dx,dy,time);const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;setNear(next);setDistance(null);if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(260,()=>{this.autoOpenLock=false;primaryRef.current()})}}}
      else{this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5),breath=Math.sin(time/720)*.006;this.player.setScale(base*(1+breath),base*(1-breath*.55))}
      this.player.setDepth(this.player.y+20);const o=currentObjective(rr.current);let targetGo:any=null;if(!exploreMode){if(o?.type==='actor')targetGo=this.actors[o.target]?.go;if(o?.type==='object')targetGo=this.objects[o.target]?.go}
      for(const[id,e]of Object.entries(this.actors)as any[]){e.go.setDepth(e.go.y+10);const d=P.Math.Distance.Between(this.player.x,this.player.y,e.go.x,e.go.y),close=d<175;if(close){const dx=this.player.x-e.go.x,dy=this.player.y-e.go.y,f:Facing=Math.abs(dy)>=Math.abs(dx)?(dy<0?'back':'front'):'side';this.setFacing(e.go,e.go.jqStyle,f,dx<0,false)}else this.setFacing(e.go,e.go.jqStyle,e.go.jqDefaultFacing||'front',false,false);if(e.go.jqLabel){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-Math.max(96,e.go.displayHeight*.83);const active=exploreMode?close:id===o?.target;e.go.jqLabel.setAlpha(active?1:.55);e.go.jqLabel.setScale(active?1.03:.92);e.go.jqLabel.jqBg?.setStrokeStyle(active?3:1,active?0xe6c861:0x79dbe8,active?.98:.45)}}
      for(const[id,e]of Object.entries(this.objects)as any[]){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-82;e.go.jqLabel.setVisible(exploreMode||id===o?.target);e.go.jqLabel.setAlpha(exploreMode?.68:1)}
      if(exploreMode){this.beacon.setVisible(false);this.targetBadge?.setVisible(false);this.guide.clear();const n=this.nearestExplore(),key=n?`${n.type}:${n.id}`:'';if(key!==this.lastNear){this.lastNear=key;setNear(n?{type:n.type,id:n.id}:null)}return}
      if(targetGo){this.beacon.setVisible(true);this.beacon.setScale(1+Math.sin(time/250)*.08);this.beacon.x=targetGo.x;this.beacon.y=targetGo.y-Math.max(105,targetGo.displayHeight*.88)+Math.sin(time/220)*4;this.targetBadge?.setVisible(true);this.targetBadge.x=targetGo.x;this.targetBadge.y=this.beacon.y-42;this.guide.clear();const dx=targetGo.x-this.player.x,dy=targetGo.y-this.player.y,d=Math.hypot(dx,dy),count=Math.min(9,Math.max(3,Math.floor(d/100)));if(d>115)for(let i=1;i<count;i++){const t=i/count;this.guide.fillStyle(0xe7c15c,.34);this.guide.fillCircle(this.player.x+dx*t,this.player.y+dy*t,3.4)}const meters=Math.max(1,Math.round(d/55));if(!this.autoTarget&&meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}const radius=Number(runtimeSettings?.settings?.interaction_radius||120),isNear=d<radius,next:Near=isNear?{type:o.type,id:o.target}:null,key=isNear?`${o.type}:${o.target}`:'';if(!this.autoTarget&&key!==this.lastNear){this.lastNear=key;setNear(next)}}else{this.beacon?.setVisible(false);this.targetBadge?.setVisible(false);this.guide?.clear();if(this.lastNear){this.lastNear='';setNear(null)}if(this.lastDistance!==-1){this.lastDistance=-1;setDistance(null)}}
    }
  }
  game=new P.Game({type:P.AUTO,parent:host.current,width:window.innerWidth,height:window.innerHeight,transparent:true,physics:{default:'arcade',arcade:{debug:false}},scene:Scene,scale:{mode:P.Scale.RESIZE,autoCenter:P.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false,powerPreference:'high-performance'}})}catch(e:any){console.error(e);setEngineError(e?.message||'Falha ao iniciar o motor gráfico.');setCloud('Motor indisponível')}})();return()=>{cancelled=true;try{game?.destroy(true)}catch{}sceneRef.current=null}},[]);

  const notes=runtime.facts.map(id=>stages.flatMap((s:any)=>[...(s.actors||[]),...(s.objects||[])]).find((x:any)=>x.fact?.id===id)?.fact).filter(Boolean),rules=runtime.decisions.map(id=>getDecision(id)).filter(Boolean),errors=runtime.wrong.map(id=>getDecision(id)).filter(Boolean),stageObjectives=stage?.objectives||[];
  const headerMode=exploreMode?'EXPLORAÇÃO LIVRE • RESULTADO PRESERVADO':isPatrol?`PLANTÃO • OCORRÊNCIA ${patrolContext?.sequence||1}/${patrolContext?.total||1}`:replayMode?'MODO REPETIÇÃO • RESULTADO ORIGINAL PRESERVADO':`ETAPA ${stageIndex+1} DE ${stages.length}`;
  return <main className="studioGame"><div ref={host} className="studioCanvas"/><div className="studioHud"><header className="topMission"><div className="brand">JURIS<span>QUEST</span></div><div className="mission"><small className={`${exploreMode?'exploreBadge':''} ${isPatrol?'modeLine':''}`}>{headerMode}</small><strong>{mission.title}</strong><span>{stage?.location||stage?.title}</span></div></header><div className="topActions"><button onClick={()=>{setNotebook(true);setProgressOpen(false);setMenuOpen(false);setScenePicker(false)}}><b>▤</b><span>Caderno</span><kbd>J</kbd></button>{exploreMode?<button onClick={()=>{setScenePicker(true);setNotebook(false);setMenuOpen(false)}}><b>⌘</b><span>Cenas</span><kbd>C</kbd></button>:<button onClick={()=>{setProgressOpen(true);setNotebook(false);setMenuOpen(false)}}><b>◫</b><span>Progresso</span><kbd>P</kbd></button>}<button onClick={()=>{setMenuOpen(true);setNotebook(false);setProgressOpen(false);setScenePicker(false)}}><b>⚙</b><span>Menu</span><kbd>Esc</kbd></button></div>{!exploreMode&&<section className="objectiveCard"><div className="kicker"><i/> {isPatrol?'PLANTÃO • OBJETIVO ATUAL':replayMode?'REPETIÇÃO • OBJETIVO ATUAL':'OBJETIVO ATUAL'}</div><h2>{objective?.title||'Etapa concluída'}</h2><p>{objective?.text||(stage?.final?(isPatrol?'Finalize esta ocorrência.':'Finalize a missão.'):'Avance para a próxima etapa.')}</p>{objective?.why&&<><button className="why" onClick={()=>setWhyOpen(v=>!v)}>› Por que isso importa?</button>{whyOpen&&<div className="whyText">{objective.why}</div>}</>}</section>}<section className="playerCard"><div className="avatarMini"><img src={svgUri(chibiSvg(character.archetype||'operational','player'))} alt=""/></div><div><b>{character.character_name||'Jogador'}</b><span>{character.role_title||'Candidato'}</span><div className="xp"><i/></div><small>{exploreMode?'Arquivo de casos':isPatrol?'Plantão ativo':replayMode?'Revisão livre':'Nvl. 1'}</small></div></section><section className="guideBar"><div className="guideIcon">!</div><div className="guideText"><b>{guidance}</b><span className={!nearIsTarget&&target?'clickHint':''}>{exploreMode?(near?'Pressione E para conversar ou examinar.':'Clique em um personagem/evidência ou explore livremente.'):nearIsTarget?'A interação está pronta. Clique em Interagir se não abrir automaticamente.':target?'O alvo correto está destacado em dourado. Clique nele para o personagem ir até lá.':'Siga o objetivo exibido.'}</span></div>{distance&&!exploreMode&&<div className="distance">Distância: {distance} m</div>}{primaryEnabled&&<button onClick={primary}><kbd>E</kbd> Interagir</button>}</section><section className="keys"><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><span>Alternativo</span></div><div><kbd>E</kbd><span>Interagir</span></div></section><div className={`sync ${cloud.includes('Falha')?'bad':''}`}>{cloud}</div></div>
  {engineError&&<ModalBox eyebrow="ERRO DO MOTOR" title="Não foi possível iniciar"><p>{engineError}</p><a className="mBtn" href="/dashboard">Voltar</a></ModalBox>}
  {overlay?.type==='brief'&&<ModalBox eyebrow={isPatrol?'CHAMADA DA CENTRAL':replayMode?'REFAZER MISSÃO':mission.briefing?.eyebrow||'MISSÃO INVESTIGATIVA'} title={mission.title} wide><p className="lead">{isPatrol?(mission.briefing?.text||mission.summary):replayMode?'Você vai refazer a missão desde o início. Seu resultado original, conclusão e XP permanecem preservados.':mission.briefing?.text||mission.summary}</p><div className="stats"><div><small>{isPatrol?'OCORRÊNCIA':'ETAPAS'}</small><b>{isPatrol?`${patrolContext?.sequence||1}/${patrolContext?.total||1}`:stages.length}</b></div><div><small>DECISÕES</small><b>{(mission.decisions||[]).length}</b></div><div><small>TEMPO</small><b>~{isPatrol?'3–8':mission.estimated_minutes||15} min</b></div></div>{mission.briefing?.learning_goal&&<div className="learning"><small>OBJETIVO DE APRENDIZAGEM</small><b>{mission.briefing.learning_goal}</b></div>}{isPatrol&&<div className="patrolStrip"><span className="priority">{String(patrolContext?.prioritySource||'gap').replaceAll('_',' ').toUpperCase()}</span><span>Mesma mecânica da Campanha</span><span>Revisão integrada</span></div>}<button className="mBtn primary" onClick={async()=>{const next={...rr.current,started:true};const ok=await persist(next);if(ok){setLocal(next);setOverlay(null)}}}>{isPatrol?'Assumir ocorrência':replayMode?'Começar repetição':'Entrar na ocorrência'}</button></ModalBox>}
  {dialog&&(()=>{const lines=dialog.actor.dialogue||[],line=lines[dialog.index]||{text:'Sem informação adicional.',choices:['Encerrar']},last=dialog.index>=Math.max(0,lines.length-1);return <ModalBox eyebrow={dialog.actor.role} title={dialog.actor.name} wide><div className="dialog"><img src={svgUri(chibiSvg(dialog.actor.visual?.archetype||dialog.actor.style||'civilian'))} alt=""/><div><p>{line.text}</p>{exploreMode&&<div className="decisionStatus">Exploração livre: esta conversa não altera nota, XP ou progresso.</div>}<div className="choices">{(line.choices||['Continuar']).map((c:string,i:number)=><button key={i} onClick={async()=>{if(!last)setDialog({...dialog,index:dialog.index+1});else if(exploreMode)setDialog(null);else if(dialog.actor.fact)await registerFact(dialog.actor.fact);else setDialog(null)}}><span>{String.fromCharCode(65+i)}</span>{last?(exploreMode?'Encerrar conversa':dialog.actor.fact?'Registrar e avançar':c):c}</button>)}</div><button className="close" onClick={()=>setDialog(null)}>Encerrar conversa</button></div></div></ModalBox>})()}
  {overlay?.type==='fact'&&<ModalBox eyebrow={overlay.explore?'EVIDÊNCIA REVISITADA':'OBJETIVO CONCLUÍDO'} title={overlay.fact.title}><div className="infoCard"><p>{overlay.fact.text}</p></div>{!overlay.explore&&<div className="learning"><small>PRÓXIMO PASSO</small><b>{nextObjectiveLabel(rr.current)}</b></div>}<button className="mBtn primary" onClick={()=>setOverlay(null)}>{overlay.explore?'Voltar ao cenário':'Ir para o próximo objetivo'}</button></ModalBox>}
  {overlay?.type==='decision'&&<ModalBox eyebrow="DECISÃO JURÍDICA" title={overlay.d.title} wide><p className="question">{overlay.d.question}</p><div className="decisionStatus">Analise o caso e escolha a providência juridicamente adequada.</div><div className="choices">{overlay.d.choices.map((c:any,i:number)=><button disabled={decisionBusy} key={i} onClick={()=>void answer(overlay.d,i)}><span>{String.fromCharCode(65+i)}</span>{c.text}</button>)}</div>{decisionBusy&&<div className="decisionStatus">Registrando sua decisão…</div>}</ModalBox>}
  {overlay?.type==='decisionError'&&<ModalBox eyebrow="NÃO FOI POSSÍVEL REGISTRAR" title={overlay.d.title} wide><div className="feedback warn">{overlay.message}</div><button className="mBtn primary" onClick={()=>setOverlay({type:'decision',d:overlay.d})}>Tentar responder novamente</button></ModalBox>}
  {overlay?.type==='feedback'&&<ModalBox eyebrow={overlay.correct?'DECISÃO CORRETA':'DECISÃO INCORRETA'} title={overlay.d.title} wide><div className={`feedback ${overlay.correct?'ok':'warn'}`}><b>{overlay.correct?'Você reconheceu corretamente o ponto jurídico central.':'A providência escolhida não resolve corretamente esta situação.'}</b><p>{overlay.choice.feedback||specificDistractor(overlay.d,overlay.choiceIndex)||'Use a explicação abaixo para reconstruir a regra antes de seguir.'}</p></div>{!overlay.correct&&specificDistractor(overlay.d,overlay.choiceIndex)&&<div className="decisionStatus bad">POR QUE A ALTERNATIVA FALHA • {specificDistractor(overlay.d,overlay.choiceIndex)}</div>}<div className="feedbackGrid"><Info label="REGRA" text={overlay.d.feedback?.rule}/><Info label="APLICAÇÃO AO CASO" text={overlay.d.feedback?.application}/><Info label="BASE LEGAL" text={overlay.d.feedback?.legal_basis}/><Info label="PEGADINHA DE PROVA" text={overlay.d.feedback?.trap}/><Info label="MEMÓRIA DE PROVA" text={overlay.d.feedback?.memory} wide/></div>{isPatrol&&overlay.patrolResult?<div className="patrolStrip"><span>{overlay.patrolResult.correct_count} acerto(s)</span><span>{overlay.patrolResult.answered_count}/{overlay.patrolResult.item_count} do turno</span>{overlay.patrolResult.complete&&<span className="priority">+{overlay.patrolResult.xp} XP</span>}</div>:null}{!isPatrol&&!overlay.saved&&!overlay.saveError&&<div className="decisionStatus">Sincronizando esta tentativa antes de liberar a próxima ação…</div>}{!isPatrol&&overlay.saveError&&<><div className="decisionStatus bad">O feedback foi preservado na tela, mas a sincronização falhou. Salve antes de continuar.</div><button className="mBtn primary" onClick={()=>void saveFeedbackState({...overlay,saveError:false})}>Tentar salvar novamente</button></>}{isPatrol?<button className="mBtn primary" onClick={()=>router.refresh()}>{overlay.patrolResult?.complete?'Ver relatório do Plantão':'Próxima ocorrência'}</button>:overlay.saved&&<button className="mBtn primary" onClick={()=>overlay.correct?setOverlay(null):setOverlay({type:'decision',d:overlay.d})}>{overlay.correct?'Consolidar e continuar':'Tentar novamente'}</button>}</ModalBox>}
  {overlay?.type==='transition'&&<ModalBox eyebrow={overlay.data.label||'TRANSIÇÃO'} title={overlay.data.title||'Próxima etapa'}><p>{overlay.data.text||'A missão avança.'}</p><button className="mBtn primary" onClick={()=>void goStage(overlay.next)}>Seguir para a próxima cena</button></ModalBox>}
  {overlay?.type==='complete'&&!isPatrol&&<ModalBox eyebrow={replayMode?'REPETIÇÃO CONCLUÍDA':'MISSÃO CONCLUÍDA'} title={mission.title} wide><p>{replayMode?'Sua repetição terminou. O resultado original foi preservado e o melhor resultado pode ser atualizado.':mission.review_plan?.completion_text}</p><div className="stats"><div><small>PROGRESSO</small><b>100%</b></div><div><small>{replayMode?'RESULTADO':'1ª TENTATIVA'}</small><b>{overlay.score}%</b></div><div><small>ERROS</small><b>{runtime.wrong.length}</b></div></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><a className="mBtn primary" href="/dashboard">Voltar à campanha</a><a className="mBtn" href={`/game/${missionId}?mode=replay`}>Refazer missão</a><a className="mBtn" href={`/game/${missionId}?mode=explore`}>Explorar cenários</a></div></ModalBox>}
  {notebook&&<ModalBox eyebrow="CADERNO" title="Fatos, regras e erros" wide><h3>Fatos coletados</h3>{notes.length?notes.map((f:any)=><Note key={f.id} title={f.title} text={f.text}/>):<p>Nenhum fato ainda.</p>}<h3>Regras consolidadas</h3>{rules.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.memory||d.feedback?.rule}/>)}<h3>Erros</h3>{errors.length?errors.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.trap}/>):<p>Nenhum erro de primeira tentativa.</p>}<button className="mBtn" onClick={()=>setNotebook(false)}>Fechar</button></ModalBox>}
  {progressOpen&&<ModalBox eyebrow={isPatrol?`OCORRÊNCIA ${patrolContext?.sequence||1}/${patrolContext?.total||1}`:`ETAPA ${stageIndex+1} DE ${stages.length}`} title={isPatrol?'Progresso da ocorrência':replayMode?'Progresso da repetição':'Progresso da missão'} wide><div className="progressList">{stageObjectives.map((o:any,i:number)=><div className={objectiveDone(o,runtime)?'done':o===objective?'current':''} key={`${o.type}-${o.target||i}`}><span>{objectiveDone(o,runtime)?'✓':i+1}</span><div><b>{o.title}</b><p>{o.text}</p></div></div>)}</div><button className="mBtn" onClick={()=>setProgressOpen(false)}>Fechar</button></ModalBox>}
  {scenePicker&&<ModalBox eyebrow="ARQUIVO DE CENAS" title="Escolha onde revisar" wide><p>Você concluiu esta missão. Pode circular livremente por qualquer cena e conversar novamente com os NPCs sem alterar seu resultado.</p><div className="scenePicker">{stages.map((s:any,i:number)=><button className={s.id===runtime.stageId?'active':''} key={s.id} onClick={()=>void goStage(s.id)}><span className="num">{i+1}</span><div><b>{s.title||s.location||`Cena ${i+1}`}</b><div className="npcHint">{s.location||s.environment}</div></div><small>{s.id===runtime.stageId?'ATUAL':'VISITAR'}</small></button>)}</div><button className="mBtn" onClick={()=>setScenePicker(false)}>Fechar</button></ModalBox>}
  {menuOpen&&<ModalBox eyebrow={exploreMode?'EXPLORAÇÃO PAUSADA':isPatrol?'PLANTÃO PAUSADO':'JOGO PAUSADO'} title={mission.title}><p>{exploreMode?'Você está em modo de exploração. Nada aqui altera sua pontuação ou conclusão.':isPatrol?'Seu Plantão permanece ativo. Você pode voltar ao painel e retomar depois.':replayMode?'A repetição é salva separadamente e não apaga sua conclusão original.':'Seu progresso é salvo antes de cada avanço da missão.'}</p><div className="choices"><button onClick={()=>setMenuOpen(false)}><span>▶</span>Continuar</button><button onClick={()=>{setMenuOpen(false);setNotebook(true)}}><span>J</span>Abrir caderno</button>{exploreMode?<button onClick={()=>{setMenuOpen(false);setScenePicker(true)}}><span>C</span>Trocar cenário</button>:<button onClick={()=>{setMenuOpen(false);setProgressOpen(true)}}><span>P</span>Ver progresso</button>}</div><a className="mBtn" href={exploreMode?'/archive':'/dashboard'}>{exploreMode?'Voltar ao Arquivo de Casos':isPatrol?'Voltar ao painel':'Sair para a campanha'}</a></ModalBox>}
  <style jsx global>{ALL_CSS}</style></main>
}

function ModalBox({eyebrow,title,children,wide=false}:{eyebrow:string;title:string;children?:any;wide?:boolean}){return <div className="modal"><section className={`sheet ${wide?'wide':''}`}><span className="ey">{eyebrow}</span><h2>{title}</h2>{children}</section></div>}
function Info({label,text,wide=false}:{label:string;text?:string;wide?:boolean}){if(!text)return null;return <div className={`info ${wide?'wide':''}`}><small>{label}</small><p>{text}</p></div>}
function Note({title,text}:{title:string;text:string;key?:any}){return <div className="note"><b>{title}</b><p>{text}</p></div>}
