'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { PALETTES as CHARACTERS, chibiSvg } from '@/lib/game/character-assets-v2';
import { svgUri } from '@/lib/game/studio-assets';
import { objectSvg, sceneSvg } from '@/lib/game/scene-assets-v3';
import { STUDIO_CSS } from '@/lib/game/studio-css';

type Props={missionId:string;mission:any;userId:string;initialCharacter?:any;initialProgress?:any;runtimeSettings?:any;replayMode?:boolean};
type Runtime={stageId:string;facts:string[];decisions:string[];wrong:string[];attemptCounts:Record<string,number>;started:boolean;completed:boolean};
type Near={type:'actor'|'object';id:string}|null;
type Overlay=null|{type:'brief'}|{type:'fact';fact:any;next:any}|{type:'decision';d:any}|{type:'feedback';d:any;choice:any;correct:boolean}|{type:'transition';next:string;data:any}|{type:'complete';score:number};
const DW=1200,DH=760;

export default function GameRuntimeProV2({missionId,mission,userId,initialCharacter,initialProgress,runtimeSettings,replayMode=false}:Props){
  const stages=useMemo(()=>[...(mission.stages||[])].sort((a:any,b:any)=>(a.order||0)-(b.order||0)),[mission]);
  const storedReplay=initialProgress?.runtime_state?.replay;
  const replayResume=replayMode&&storedReplay&&!storedReplay.completed?storedReplay:null;
  const resume=replayMode?(replayResume||{}):(initialProgress?.runtime_state||{});
  const freshReplay=replayMode&&!replayResume;
  const initial:Runtime=freshReplay
    ?{stageId:stages[0]?.id||'',facts:[],decisions:[],wrong:[],attemptCounts:{},started:false,completed:false}
    :{stageId:resume.stageId||initialProgress?.current_stage||stages[0]?.id||'',facts:resume.facts||initialProgress?.facts||[],decisions:resume.decisions||[],wrong:resume.wrong||initialProgress?.mistakes||[],attemptCounts:resume.attemptCounts||initialProgress?.decisions||{},started:resume.started??!!initialProgress,completed:replayMode?!!resume.completed:initialProgress?.status==='completed'};
  const initialOverlay:Overlay=initial.completed?{type:'complete',score:Number(replayMode?initialProgress?.runtime_state?.replay_score:initialProgress?.score_best||initialProgress?.score_first_try||100)}:initial.started?null:{type:'brief'};
  const [runtime,setRuntime]=useState(initial); const rr=useRef(initial);
  const [near,setNear]=useState<Near>(null); const nr=useRef<Near>(null);
  const [overlay,setOverlay]=useState<Overlay>(initialOverlay);
  const [dialog,setDialog]=useState<any>(null); const [notebook,setNotebook]=useState(false); const [progressOpen,setProgressOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false); const [whyOpen,setWhyOpen]=useState(false);
  const [ready,setReady]=useState(false); const [cloud,setCloud]=useState('Sincronizando…'); const [engineError,setEngineError]=useState(''); const [distance,setDistance]=useState<number|null>(null);
  const host=useRef<HTMLDivElement>(null); const sceneRef=useRef<any>(null); const sb=useRef(createClient()); const saveChain=useRef<Promise<boolean>>(Promise.resolve(true));
  const blockedRef=useRef(false); const primaryRef=useRef<()=>void>(()=>{});
  const character=initialCharacter||{character_name:'Jogador',role_title:'Candidato',archetype:'operational'};
  const stage=stages.find((s:any)=>s.id===runtime.stageId)||stages[0]; const stageIndex=Math.max(0,stages.findIndex((s:any)=>s.id===stage?.id));
  useEffect(()=>{rr.current=runtime},[runtime]); useEffect(()=>{nr.current=near},[near]);

  function entityForObjective(o:any,r=rr.current){const s=stages.find((x:any)=>x.id===r.stageId);if(!s||!o)return null;if(o.type==='actor')return(s.actors||[]).find((x:any)=>x.id===o.target)||null;if(o.type==='object')return(s.objects||[]).find((x:any)=>x.id===o.target)||null;return null}
  function factIdForObjective(o:any,r=rr.current){return entityForObjective(o,r)?.fact?.id||o?.target}
  const hasFact=(id:string,r=rr.current)=>r.facts.includes(id),hasDecision=(id:string,r=rr.current)=>r.decisions.includes(id),getDecision=(id:string)=>(mission.decisions||[]).find((d:any)=>d.id===id);
  function objectiveDone(o:any,r=rr.current){if(!o)return false;if(o.type==='actor'||o.type==='object')return hasFact(factIdForObjective(o,r),r);if(o.type==='decision')return hasDecision(o.target,r);return false}
  function currentObjective(r=rr.current){const s=stages.find((x:any)=>x.id===r.stageId);return(s?.objectives||[]).find((o:any)=>o.type==='advance'||!objectiveDone(o,r))||null}
  function decisionReady(d:any,r=rr.current){return!!d&&(d.requires_facts||[]).every((f:string)=>hasFact(f,r))&&(d.depends_on||[]).every((x:string)=>hasDecision(x,r))}
  function overallProgress(r=rr.current){const os=stages.flatMap((s:any)=>(s.objectives||[]).filter((o:any)=>o.type!=='advance'));return os.length?Math.round(os.filter((o:any)=>objectiveDone(o,r)).length/os.length*100):0}
  function nextObjectiveLabel(r:Runtime){const o=currentObjective(r);if(!o)return'Etapa concluída';const e=entityForObjective(o,r);if(o.type==='actor')return`Fale com ${e?.name||o.title}`;if(o.type==='object')return e?.interaction_text||`Examine ${e?.name||o.title}`;return o.title}

  function replayPayload(next:Runtime,complete=false,score:number|null=null){
    const root={...(initialProgress?.runtime_state||{})};
    return {user_id:userId,mission_id:missionId,status:initialProgress?.status||'completed',current_stage:initialProgress?.current_stage||stages.at(-1)?.id||next.stageId,progress_percent:Number(initialProgress?.progress_percent??100),score_first_try:initialProgress?.score_first_try??null,score_best:complete?Math.max(Number(initialProgress?.score_best||0),Number(score||0)):initialProgress?.score_best??null,mistakes:initialProgress?.mistakes||[],facts:initialProgress?.facts||[],decisions:initialProgress?.decisions||{},runtime_state:{...root,replay:next,replay_updated_at:new Date().toISOString(),...(complete?{replay_score:score}: {})},started_at:initialProgress?.started_at||new Date().toISOString(),completed_at:initialProgress?.completed_at||new Date().toISOString(),updated_at:new Date().toISOString()};
  }
  function normalPayload(next:Runtime,complete=false,score:number|null=null){return{user_id:userId,mission_id:missionId,status:complete?'completed':'in_progress',current_stage:next.stageId,progress_percent:complete?100:overallProgress(next),score_first_try:complete?score:null,score_best:complete?score:null,mistakes:next.wrong,facts:next.facts,decisions:next.attemptCounts,runtime_state:next,started_at:initialProgress?.started_at||new Date().toISOString(),completed_at:complete?new Date().toISOString():null,updated_at:new Date().toISOString()}}
  function persist(next:Runtime,complete=false,score:number|null=null){
    saveChain.current=saveChain.current.then(async()=>{setCloud(replayMode?'Salvando repetição…':'Salvando…');const payload=replayMode?replayPayload(next,complete,score):normalPayload(next,complete,score);const{error}=await sb.current.from('mission_progress').upsert(payload,{onConflict:'user_id,mission_id'});if(error){console.error('mission save failed',error);setCloud('Falha ao salvar');return false}setCloud(replayMode?'Repetição salva':'Progresso salvo');return true}).catch(e=>{console.error(e);setCloud('Falha ao salvar');return false});return saveChain.current
  }
  function setLocal(next:Runtime){rr.current=next;setRuntime(next)}
  async function registerFact(f:any){if(!f?.id)return false;if(hasFact(f.id)){setDialog(null);return true}const next={...rr.current,facts:[...rr.current.facts,f.id]};const ok=await persist(next);if(!ok)return false;setLocal(next);setDialog(null);setOverlay({type:'fact',fact:f,next:currentObjective(next)});return true}
  async function nextDbAttempt(decisionId:string){const{data,error}=await sb.current.from('decision_attempts').select('attempt_no').eq('user_id',userId).eq('mission_id',missionId).eq('decision_id',decisionId).order('attempt_no',{ascending:false}).limit(1).maybeSingle();if(error){console.error(error);return null}return Number(data?.attempt_no||0)+1}
  async function answer(d:any,i:number){const c=d?.choices?.[i];if(!c)return;const r=rr.current,runAttempt=(r.attemptCounts[d.id]||0)+1,dbAttempt=await nextDbAttempt(d.id);if(!dbAttempt){setCloud('Falha ao registrar decisão');return}const correct=!!c.correct,wrong=!correct&&runAttempt===1&&!r.wrong.includes(d.id)?[...r.wrong,d.id]:r.wrong,base={...r,wrong,attemptCounts:{...r.attemptCounts,[d.id]:runAttempt}};setCloud('Registrando decisão…');const{error}=await sb.current.from('decision_attempts').insert({user_id:userId,mission_id:missionId,decision_id:d.id,attempt_no:dbAttempt,selected_index:i,selected_text:c.text,correct,mode:replayMode?'replay':'mission',feedback_snapshot:d.feedback||{}});if(error){console.error(error);setCloud('Falha ao registrar decisão');return}const next=correct?{...base,decisions:base.decisions.includes(d.id)?base.decisions:[...base.decisions,d.id]}:base;const ok=await persist(next);if(!ok)return;setLocal(next);setOverlay({type:'feedback',d,choice:c,correct})}
  async function finish(){const r=rr.current,total=Math.max(1,(mission.decisions||[]).length),score=Math.max(0,Math.round((total-r.wrong.length)/total*100)),next={...r,completed:true};const ok=await persist(next,true,score);if(!ok)return;setLocal(next);setOverlay({type:'complete',score})}
  async function goStage(id:string){const next={...rr.current,stageId:id};const ok=await persist(next);if(!ok)return;setLocal(next);setOverlay(null);sceneRef.current?.buildStage?.(stages.find((s:any)=>s.id===id))}
  function primary(){const r=rr.current,o=currentObjective(r);if(o?.type==='actor'||o?.type==='object'){const n=nr.current;if(n&&n.type===o.type&&n.id===o.target){const s=stages.find((x:any)=>x.id===r.stageId);if(o.type==='actor'){const a=(s?.actors||[]).find((x:any)=>x.id===o.target);if(a)setDialog({actor:a,index:0})}else{const obj=(s?.objects||[]).find((x:any)=>x.id===o.target);if(obj?.fact)void registerFact(obj.fact)}}return}if(o?.type==='decision'){const d=getDecision(o.target);if(decisionReady(d,r))setOverlay({type:'decision',d});return}if(o?.type==='advance'){const i=stages.findIndex((x:any)=>x.id===r.stageId),next=stages[i+1];if(next)setOverlay({type:'transition',next:next.id,data:stages[i]?.transition||{}});return}const s=stages.find((x:any)=>x.id===r.stageId);if(!o&&s?.final)void finish()}
  primaryRef.current=primary;

  const objective=currentObjective(runtime),target=entityForObjective(objective,runtime),nearIsTarget=!!(objective&&(objective.type==='actor'||objective.type==='object')&&near&&near.type===objective.type&&near.id===objective.target),decisionCanOpen=objective?.type==='decision'?decisionReady(getDecision(objective.target),runtime):false;
  const primaryEnabled=ready&&(nearIsTarget||(objective?.type==='decision'&&decisionCanOpen)||objective?.type==='advance'||(!objective&&stage?.final));
  const guidance=!ready?'Preparando cenário':objective?.type==='actor'?(nearIsTarget?`Fale com ${target?.name||objective.title}`:`Vá até ${target?.name||objective.title}`):objective?.type==='object'?(nearIsTarget?(target?.interaction_text||`Examine ${target?.name||objective.title}`):`Vá até ${target?.name||objective.title}`):objective?.type==='decision'?(decisionCanOpen?objective.title:'Complete as evidências anteriores'):objective?.type==='advance'?(objective.title||'Avance para a próxima etapa'):(!objective&&stage?.final?'Concluir missão':'Explore o cenário');
  useEffect(()=>{setWhyOpen(false)},[runtime.stageId,objective?.target,objective?.type]);
  useEffect(()=>{blockedRef.current=!!overlay||!!dialog||notebook||progressOpen||menuOpen||!runtime.started},[overlay,dialog,notebook,progressOpen,menuOpen,runtime.started]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.repeat)return;const k=e.key.toLowerCase();if(k==='j'&&!overlay&&!dialog){setNotebook(v=>!v);setProgressOpen(false);setMenuOpen(false)}else if(k==='p'&&!overlay&&!dialog){setProgressOpen(v=>!v);setNotebook(false);setMenuOpen(false)}else if(e.key==='Escape'){if(notebook)setNotebook(false);else if(progressOpen)setProgressOpen(false);else if(menuOpen)setMenuOpen(false);else if(dialog)setDialog(null);else if(!overlay)setMenuOpen(true)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[overlay,dialog,notebook,progressOpen,menuOpen]);

  useEffect(()=>{let game:any,cancelled=false;(async()=>{try{const mod:any=await import('phaser');if(cancelled||!host.current)return;const P:any=mod.default||mod;class Scene extends P.Scene{
    player:any;actors:Record<string,any>={};objects:Record<string,any>={};keys:any;cursors:any;worldW=DW;worldH=DH;isDesktop=true;beacon:any;guide:any;lastNear='';lastDistance=-1;rain:any[]=[];
    constructor(){super('pro-v2')}
    preload(){this.load.image('bg-parking',svgUri(sceneSvg('parking_night')));this.load.image('bg-station',svgUri(sceneSvg('police_station')));this.load.image('bg-court',svgUri(sceneSvg('courtroom')));for(const k of Object.keys(CHARACTERS))this.load.image(`char-${k}`,svgUri(chibiSvg(k)));this.load.image('char-player',svgUri(chibiSvg(character.archetype||'operational','player')));this.load.image('obj-camera',svgUri(objectSvg('camera')));this.load.image('obj-evidence',svgUri(objectSvg('evidence')));this.load.image('obj-document',svgUri(objectSvg('document')))}
    create(){sceneRef.current=this;this.cursors=this.input.keyboard?.createCursorKeys();this.keys=this.input.keyboard?.addKeys('W,A,S,D,SHIFT,E,ENTER');this.input.keyboard?.on('keydown-E',()=>primaryRef.current());this.input.keyboard?.on('keydown-ENTER',()=>primaryRef.current());this.buildStage(stages.find((x:any)=>x.id===rr.current.stageId)||stages[0]);this.scale.on('resize',()=>this.buildStage(stages.find((x:any)=>x.id===rr.current.stageId)||stages[0]));setReady(true);setCloud(replayMode?'Modo repetição':'Progresso salvo')}
    mapX(x:number){const p=Math.max(34,this.worldW*.025);return p+(x/DW)*(this.worldW-p*2)} mapY(y:number){const t=Math.max(84,this.worldH*.09),b=Math.max(86,this.worldH*.1);return t+(y/DH)*(this.worldH-t-b)}
    configure(){this.isDesktop=this.scale.width>=900;this.worldW=this.isDesktop?this.scale.width:DW;this.worldH=this.isDesktop?this.scale.height:DH;this.physics.world.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setZoom(this.isDesktop?1:Number(runtimeSettings?.settings?.camera_zoom_mobile||.86));if(this.isDesktop){this.cameras.main.stopFollow();this.cameras.main.setScroll(0,0)}}
    bgKey(s:any){return s.environment==='police_station'?'bg-station':s.environment==='courtroom'?'bg-court':'bg-parking'}
    label(name:string,role:string){const c=this.add.container(0,0).setDepth(1200),w=Math.max(104,Math.min(174,name.length*7+30)),bg=this.add.rectangle(0,0,w,31,0x06151c,.78).setStrokeStyle(1,0x6bcbd7,.42),t=this.add.text(0,-4,name,{fontFamily:'Inter,Arial',fontSize:'10px',fontStyle:'bold',color:'#f7fbfc'}).setOrigin(.5),r=this.add.text(0,8,role,{fontFamily:'Inter,Arial',fontSize:'7px',fontStyle:'bold',color:'#8bdbe5'}).setOrigin(.5);c.add([bg,t,r]);return c}
    actor(def:any,isPlayer=false){const x=this.mapX(def.position?.x||600),y=this.mapY(def.position?.y||650),style=def.visual?.archetype||def.style||'civilian',img=this.physics.add.image(x,y,isPlayer?'char-player':`char-${style}`).setOrigin(.5,.84),scale=Math.max(.38,Math.min(.58,this.worldH/1650));img.setScale(scale);img.body.setSize(74,46);img.body.setCollideWorldBounds(true);img.setDepth(y+20);(img as any).jqLabel=isPlayer?null:this.label(def.name,def.role);return img}
    prop(def:any){const x=this.mapX(def.position?.x||500),y=this.mapY(def.position?.y||300),key=def.kind==='camera'?'obj-camera':def.kind==='evidence'?'obj-evidence':'obj-document',img=this.add.image(x,y,key).setScale(.5).setDepth(y+6);(img as any).jqLabel=this.label(def.name||'Objeto',def.role||'EVIDÊNCIA');(img as any).jqLabel.setVisible(false);return img}
    ambient(s:any){if(s.environment==='parking_night'){for(const x of [180,520,1080,1430]){const light=this.add.circle(x/1600*this.worldW,155/900*this.worldH,Math.max(75,this.worldH*.11),0xffd77d,.045).setDepth(-70);light.setBlendMode(P.BlendModes.ADD)}for(let i=0;i<34;i++){const line=this.add.rectangle(Math.random()*this.worldW,Math.random()*this.worldH,1,14,0xb7ecff,.12).setRotation(-.16).setDepth(40);this.rain.push(line)}}else{const tint=this.add.rectangle(this.worldW/2,this.worldH/2,this.worldW,this.worldH,s.environment==='courtroom'?0xffe1ad:0xc7eff0,.02).setDepth(-70);tint.setBlendMode(P.BlendModes.ADD)}}
    buildStage(s:any){if(!s)return;this.children.removeAll(true);this.rain=[];this.actors={};this.objects={};this.lastNear='';setNear(null);this.configure();this.add.image(this.worldW/2,this.worldH/2,this.bgKey(s)).setDisplaySize(this.worldW,this.worldH).setDepth(-100);this.ambient(s);this.player=this.actor({position:s.player_spawn||{x:600,y:650}},true);for(const a of s.actors||[])this.actors[a.id]={def:a,go:this.actor(a)};for(const o of s.objects||[])this.objects[o.id]={def:o,go:this.prop(o)};this.beacon=this.add.circle(0,0,22,0x55e6ff,.1).setStrokeStyle(3,0x74ecf7,.92).setDepth(1500);this.guide=this.add.graphics().setDepth(1240);if(!this.isDesktop)this.cameras.main.startFollow(this.player,true,.12,.12)}
    update(time:number){if(!this.player)return;for(const r of this.rain){r.y+=3.4;if(r.y>this.worldH){r.y=-20;r.x=Math.random()*this.worldW}}const speed=this.keys?.SHIFT?.isDown?305:205,kx=((this.keys?.D?.isDown||this.cursors?.right?.isDown)?1:0)-((this.keys?.A?.isDown||this.cursors?.left?.isDown)?1:0),ky=((this.keys?.S?.isDown||this.cursors?.down?.isDown)?1:0)-((this.keys?.W?.isDown||this.cursors?.up?.isDown)?1:0),len=Math.hypot(kx,ky);if(!blockedRef.current&&len>.05){this.player.body.setVelocity(kx/len*speed,ky/len*speed);this.player.setFlipX(kx<0);this.player.angle=Math.sin(time/90)*1.05}else{this.player.body.setVelocity(0,0);this.player.angle=0}this.player.setDepth(this.player.y+20);const o=currentObjective(rr.current);let targetGo:any=null;if(o?.type==='actor')targetGo=this.actors[o.target]?.go;if(o?.type==='object')targetGo=this.objects[o.target]?.go;for(const[id,e]of Object.entries(this.actors)as any[]){e.go.setDepth(e.go.y+10);if(e.go.jqLabel){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-Math.max(82,e.go.displayHeight*.76);const active=id===o?.target;e.go.jqLabel.setAlpha(active?1:.34);e.go.jqLabel.setScale(active?1:.88)}}for(const[id,e]of Object.entries(this.objects)as any[]){e.go.jqLabel.x=e.go.x;e.go.jqLabel.y=e.go.y-72;e.go.jqLabel.setVisible(id===o?.target)}if(targetGo){this.beacon.setVisible(true);this.beacon.x=targetGo.x;this.beacon.y=targetGo.y-Math.max(92,targetGo.displayHeight*.82)+Math.sin(time/220)*4;this.guide.clear();const dx=targetGo.x-this.player.x,dy=targetGo.y-this.player.y,d=Math.hypot(dx,dy),count=Math.min(10,Math.max(4,Math.floor(d/85)));if(d>115)for(let i=1;i<count;i++){const t=i/count;this.guide.fillStyle(0x6be6f2,.48);this.guide.fillCircle(this.player.x+dx*t,this.player.y+dy*t,3.5)}const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}const radius=Number(runtimeSettings?.settings?.interaction_radius||120),isNear=d<radius,next:Near=isNear?{type:o.type,id:o.target}:null,key=isNear?`${o.type}:${o.target}`:'';if(key!==this.lastNear){this.lastNear=key;setNear(next)}}else{this.beacon?.setVisible(false);this.guide?.clear();if(this.lastNear){this.lastNear='';setNear(null)}if(this.lastDistance!==-1){this.lastDistance=-1;setDistance(null)}}}
  }game=new P.Game({type:P.AUTO,parent:host.current,width:window.innerWidth,height:window.innerHeight,transparent:true,physics:{default:'arcade',arcade:{debug:false}},scene:Scene,scale:{mode:P.Scale.RESIZE,autoCenter:P.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false,powerPreference:'high-performance'}})}catch(e:any){console.error(e);setEngineError(e?.message||'Falha ao iniciar o motor gráfico.');setCloud('Motor indisponível')}})();return()=>{cancelled=true;try{game?.destroy(true)}catch{}sceneRef.current=null}},[]);

  const notes=runtime.facts.map(id=>stages.flatMap((s:any)=>[...(s.actors||[]),...(s.objects||[])]).find((x:any)=>x.fact?.id===id)?.fact).filter(Boolean),rules=runtime.decisions.map(id=>getDecision(id)).filter(Boolean),errors=runtime.wrong.map(id=>getDecision(id)).filter(Boolean),stageObjectives=stage?.objectives||[];
  return <main className="studioGame"><div ref={host} className="studioCanvas"/><div className="studioHud"><header className="topMission"><div className="brand">JURIS<span>QUEST</span></div><div className="mission"><small>{replayMode?'MODO REPETIÇÃO • RESULTADO ORIGINAL PRESERVADO':`ETAPA ${stageIndex+1} DE ${stages.length}`}</small><strong>{mission.title}</strong><span>{stage?.location||stage?.title}</span></div></header><div className="topActions"><button onClick={()=>{setNotebook(true);setProgressOpen(false);setMenuOpen(false)}}><b>▤</b><span>Caderno</span><kbd>J</kbd></button><button onClick={()=>{setProgressOpen(true);setNotebook(false);setMenuOpen(false)}}><b>◫</b><span>Progresso</span><kbd>P</kbd></button><button onClick={()=>{setMenuOpen(true);setNotebook(false);setProgressOpen(false)}}><b>⚙</b><span>Menu</span><kbd>Esc</kbd></button></div><section className="objectiveCard"><div className="kicker"><i/> {replayMode?'REPETIÇÃO • OBJETIVO ATUAL':'OBJETIVO ATUAL'}</div><h2>{objective?.title||'Etapa concluída'}</h2><p>{objective?.text||(stage?.final?'Finalize a missão.':'Avance para a próxima etapa.')}</p>{objective?.why&&<><button className="why" onClick={()=>setWhyOpen(v=>!v)}>› Por que isso importa?</button>{whyOpen&&<div className="whyText">{objective.why}</div>}</>}</section><section className="playerCard"><div className="avatarMini"><img src={svgUri(chibiSvg(character.archetype||'operational','player'))} alt=""/></div><div><b>{character.character_name||'Jogador'}</b><span>{character.role_title||'Candidato'}</span><div className="xp"><i/></div><small>{replayMode?'Revisão livre':'Nvl. 1'}</small></div></section><section className="guideBar"><div className="guideIcon">!</div><div className="guideText"><b>{guidance}</b><span>{nearIsTarget?'Pressione E ou clique em Interagir.':'Siga o marcador luminoso.'}</span></div>{distance&&<div className="distance">Distância: {distance} m</div>}{primaryEnabled&&<button onClick={primary}><kbd>E</kbd> Interagir</button>}</section><section className="keys"><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><span>Mover</span></div><div><kbd>Shift</kbd><span>Correr</span></div><div><kbd>E</kbd><span>Interagir</span></div></section><div className={`sync ${cloud.includes('Falha')?'bad':''}`}>{cloud}</div></div>
  {engineError&&<ModalBox eyebrow="ERRO DO MOTOR" title="Não foi possível iniciar"><p>{engineError}</p><a className="mBtn" href="/dashboard">Voltar</a></ModalBox>}
  {overlay?.type==='brief'&&<ModalBox eyebrow={replayMode?'REFAZER MISSÃO':mission.briefing?.eyebrow||'MISSÃO INVESTIGATIVA'} title={mission.title} wide><p className="lead">{replayMode?'Você vai refazer a missão desde o início. Seu resultado original, conclusão e XP permanecem preservados.':mission.briefing?.text||mission.summary}</p><div className="stats"><div><small>ETAPAS</small><b>{stages.length}</b></div><div><small>DECISÕES</small><b>{(mission.decisions||[]).length}</b></div><div><small>TEMPO</small><b>~{mission.estimated_minutes||15} min</b></div></div><div className="learning"><small>OBJETIVO DE APRENDIZAGEM</small><b>{mission.briefing?.learning_goal}</b></div><button className="mBtn primary" onClick={async()=>{const next={...rr.current,started:true};const ok=await persist(next);if(ok){setLocal(next);setOverlay(null)}}}>{replayMode?'Começar repetição':'Entrar na ocorrência'}</button></ModalBox>}
  {dialog&&(()=>{const lines=dialog.actor.dialogue||[],line=lines[dialog.index]||{text:'Sem informação adicional.',choices:['Encerrar']},last=dialog.index>=Math.max(0,lines.length-1);return <ModalBox eyebrow={dialog.actor.role} title={dialog.actor.name} wide><div className="dialog"><img src={svgUri(chibiSvg(dialog.actor.visual?.archetype||dialog.actor.style||'civilian'))} alt=""/><div><p>{line.text}</p><div className="choices">{(line.choices||['Continuar']).map((c:string,i:number)=><button key={i} onClick={async()=>{if(!last)setDialog({...dialog,index:dialog.index+1});else if(dialog.actor.fact)await registerFact(dialog.actor.fact);else setDialog(null)}}><span>{String.fromCharCode(65+i)}</span>{last&&dialog.actor.fact?'Registrar e avançar':c}</button>)}</div><button className="close" onClick={()=>setDialog(null)}>Encerrar conversa</button></div></div></ModalBox>})()}
  {overlay?.type==='fact'&&<ModalBox eyebrow="OBJETIVO CONCLUÍDO" title={overlay.fact.title}><div className="infoCard"><p>{overlay.fact.text}</p></div><div className="learning"><small>PRÓXIMO PASSO</small><b>{nextObjectiveLabel(rr.current)}</b></div><button className="mBtn primary" onClick={()=>setOverlay(null)}>Ir para o próximo objetivo</button></ModalBox>}
  {overlay?.type==='decision'&&<ModalBox eyebrow="DECISÃO JURÍDICA" title={overlay.d.title} wide><p className="question">{overlay.d.question}</p><div className="choices">{overlay.d.choices.map((c:any,i:number)=><button key={i} onClick={()=>void answer(overlay.d,i)}><span>{String.fromCharCode(65+i)}</span>{c.text}</button>)}</div></ModalBox>}
  {overlay?.type==='feedback'&&<ModalBox eyebrow={overlay.correct?'BOA ESCOLHA':'INFORMAÇÃO IMPORTANTE'} title={overlay.d.title} wide><div className={`feedback ${overlay.correct?'ok':'warn'}`}>{overlay.choice.feedback}</div><div className="feedbackGrid"><Info label="REGRA" text={overlay.d.feedback?.rule}/><Info label="APLICAÇÃO" text={overlay.d.feedback?.application}/><Info label="BASE LEGAL" text={overlay.d.feedback?.legal_basis}/><Info label="PEGADINHA" text={overlay.d.feedback?.trap}/><Info label="MEMÓRIA" text={overlay.d.feedback?.memory} wide/></div><button className="mBtn primary" onClick={()=>overlay.correct?setOverlay(null):setOverlay({type:'decision',d:overlay.d})}>{overlay.correct?'Consolidar e continuar':'Tentar novamente'}</button></ModalBox>}
  {overlay?.type==='transition'&&<ModalBox eyebrow={overlay.data.label||'TRANSIÇÃO'} title={overlay.data.title||'Próxima etapa'}><p>{overlay.data.text||'A missão avança.'}</p><button className="mBtn primary" onClick={()=>void goStage(overlay.next)}>Seguir para a próxima cena</button></ModalBox>}
  {overlay?.type==='complete'&&<ModalBox eyebrow={replayMode?'REPETIÇÃO CONCLUÍDA':'MISSÃO CONCLUÍDA'} title={mission.title} wide><p>{replayMode?'Sua repetição terminou. O resultado original foi preservado e o melhor resultado pode ser atualizado.':mission.review_plan?.completion_text}</p><div className="stats"><div><small>PROGRESSO</small><b>100%</b></div><div><small>{replayMode?'RESULTADO':'1ª TENTATIVA'}</small><b>{overlay.score}%</b></div><div><small>ERROS</small><b>{runtime.wrong.length}</b></div></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><a className="mBtn primary" href="/dashboard">Voltar à campanha</a><a className="mBtn" href={`/game/${missionId}?mode=replay`}>Refazer missão</a></div></ModalBox>}
  {notebook&&<ModalBox eyebrow="CADERNO" title="Fatos, regras e erros" wide><h3>Fatos coletados</h3>{notes.length?notes.map((f:any)=><Note key={f.id} title={f.title} text={f.text}/>):<p>Nenhum fato ainda.</p>}<h3>Regras consolidadas</h3>{rules.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.memory||d.feedback?.rule}/>)}<h3>Erros</h3>{errors.length?errors.map((d:any)=><Note key={d.id} title={d.title} text={d.feedback?.trap}/>):<p>Nenhum erro de primeira tentativa.</p>}<button className="mBtn" onClick={()=>setNotebook(false)}>Fechar</button></ModalBox>}
  {progressOpen&&<ModalBox eyebrow={`ETAPA ${stageIndex+1} DE ${stages.length}`} title={replayMode?'Progresso da repetição':'Progresso da missão'} wide><div className="progressList">{stageObjectives.map((o:any,i:number)=><div className={objectiveDone(o,runtime)?'done':o===objective?'current':''} key={`${o.type}-${o.target||i}`}><span>{objectiveDone(o,runtime)?'✓':i+1}</span><div><b>{o.title}</b><p>{o.text}</p></div></div>)}</div><button className="mBtn" onClick={()=>setProgressOpen(false)}>Fechar</button></ModalBox>}
  {menuOpen&&<ModalBox eyebrow="JOGO PAUSADO" title={mission.title}><p>{replayMode?'A repetição é salva separadamente e não apaga sua conclusão original.':'Seu progresso é salvo antes de cada avanço da missão.'}</p><div className="choices"><button onClick={()=>setMenuOpen(false)}><span>▶</span>Continuar jogando</button><button onClick={()=>{setMenuOpen(false);setNotebook(true)}}><span>J</span>Abrir caderno</button><button onClick={()=>{setMenuOpen(false);setProgressOpen(true)}}><span>P</span>Ver progresso</button></div><a className="mBtn" href="/dashboard">Sair para a campanha</a></ModalBox>}
  <style jsx global>{STUDIO_CSS}</style></main>
}
function ModalBox({eyebrow,title,children,wide=false}:{eyebrow:string;title:string;children?:any;wide?:boolean}){return <div className="modal"><section className={`sheet ${wide?'wide':''}`}><span className="ey">{eyebrow}</span><h2>{title}</h2>{children}</section></div>}
function Info({label,text,wide=false}:{label:string;text?:string;wide?:boolean}){if(!text)return null;return <div className={`info ${wide?'wide':''}`}><small>{label}</small><p>{text}</p></div>}
function Note({title,text}:{title:string;text:string;key?:any}){return <div className="note"><b>{title}</b><p>{text}</p></div>}
