'use client';

import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type UserRow={id:string;email?:string;created_at?:string;last_sign_in_at?:string;profile?:{display_name?:string;role?:string}|null;grants?:any[]};

export default function UserManager(){
  const [users,setUsers]=useState<UserRow[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [days,setDays]=useState(30);
  const sb=createClient();

  async function call(body:any){const {data,error}=await sb.functions.invoke('admin-user-manager',{body});if(error)throw new Error(error.message||'Falha administrativa.');if(data?.error)throw new Error(data.message||data.error);return data}
  async function refresh(){setLoading(true);setMessage('');try{const data=await call({action:'list',page:1,per_page:200});setUsers(data.users||[])}catch(e:any){setMessage(e.message||'Falha ao listar usuários.')}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[]);
  async function createUser(e:FormEvent){e.preventDefault();setBusy('create');setMessage('');try{await call({action:'create',email:email.trim().toLowerCase(),password,display_name:name.trim(),global_access:true,access_type:'subscription',days,notes:'Acesso criado pelo painel ADM'});setName('');setEmail('');setPassword('');setMessage('Conta criada e acesso concedido.');await refresh()}catch(e:any){setMessage(e.message||'Falha ao criar conta.')}finally{setBusy('')}}
  async function grant(userId:string,duration:number|null){setBusy(`g:${userId}`);setMessage('');try{await call({action:'grant',user_id:userId,global_access:true,access_type:'subscription',days:duration||undefined,notes:duration?`Acesso global por ${duration} dias`:'Acesso global sem expiração'});setMessage('Acesso concedido.');await refresh()}catch(e:any){setMessage(e.message||'Falha ao conceder acesso.')}finally{setBusy('')}}
  async function revoke(grantId:string){setBusy(`r:${grantId}`);setMessage('');try{await call({action:'revoke',grant_id:grantId});setMessage('Acesso revogado.');await refresh()}catch(e:any){setMessage(e.message||'Falha ao revogar acesso.')}finally{setBusy('')}}

  return <div className="umWrap">
    <section className="umHero"><div><span className="umKicker">ACCESS CONTROL</span><h1>Usuários e Acessos</h1><p>Criação de contas, trial, assinatura manual e revogação com autorização administrativa real.</p></div><a className="btn" href="/admin">Voltar ao ADM</a></section>
    {message&&<div className="umMsg">{message}</div>}
    <section className="umGrid"><form className="umPanel" onSubmit={createUser}><span className="umKicker">NOVA CONTA</span><h2>Criar acesso</h2><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha inicial<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label><label>Duração do acesso<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={365}>365 dias</option></select></label><button className="btn primary" disabled={busy==='create'}>{busy==='create'?'Criando…':'Criar conta + liberar acesso'}</button></form>
    <section className="umPanel users"><div className="umHead"><div><span className="umKicker">BASE DE USUÁRIOS</span><h2>{loading?'Carregando…':`${users.length} contas`}</h2></div><button className="btn" onClick={()=>void refresh()} disabled={loading}>Atualizar</button></div><div className="umList">{users.map(u=>{const active=(u.grants||[]).filter(g=>g.status==='active'&&(!g.ends_at||new Date(g.ends_at)>new Date()));return <article className="umUser" key={u.id}><div className="umIdentity"><b>{u.profile?.display_name||u.email||'Usuário'}</b><span>{u.email}</span><small>{u.profile?.role==='admin'?'ADMINISTRADOR':'ALUNO'} • último acesso {u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString('pt-BR'):'nunca'}</small></div><div className="umGrants">{active.length?active.map(g=><span className={`grant ${g.access_type}`} key={g.id}>{g.access_type}{g.ends_at?` • até ${new Date(g.ends_at).toLocaleDateString('pt-BR')}`:' • permanente'}{g.access_type!=='admin'&&<button title="Revogar" disabled={busy===`r:${g.id}`} onClick={()=>void revoke(g.id)}>×</button>}</span>):<span className="grant none">SEM ACESSO ATIVO</span>}</div>{u.profile?.role!=='admin'&&<div className="umActions"><button onClick={()=>void grant(u.id,30)} disabled={busy===`g:${u.id}`}>+30 dias</button><button onClick={()=>void grant(u.id,90)} disabled={busy===`g:${u.id}`}>+90 dias</button><button onClick={()=>void grant(u.id,null)} disabled={busy===`g:${u.id}`}>Permanente</button></div>}</article>})}</div></section></section>
    <style jsx global>{`.umWrap{max-width:1450px;margin:auto;padding:24px 18px 70px}.umHero{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;padding:24px;border:1px solid #2f4c55;border-radius:20px;background:linear-gradient(135deg,#10252b,#08171b)}.umHero h1{margin:6px 0;font-size:32px}.umHero p{margin:0;color:#8ca3a7}.umKicker{font:900 9px ui-monospace;letter-spacing:.14em;color:#6fd3dc}.umMsg{margin:12px 0;padding:11px 13px;border:1px solid #42636c;border-radius:10px;background:#0b2026}.umGrid{display:grid;grid-template-columns:330px 1fr;gap:14px;margin-top:14px}.umPanel{border:1px solid #2e4b54;border-radius:16px;background:#0a1c21;padding:17px}.umPanel h2{margin:5px 0 14px}.umPanel label{display:block;font-size:10px;color:#9eb1b5;margin:10px 0}.umPanel input,.umPanel select{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:10px;background:#061419;border:1px solid #35545d;border-radius:9px;color:#edf3f1}.umHead{display:flex;justify-content:space-between;align-items:center}.umList{display:grid;gap:8px}.umUser{display:grid;grid-template-columns:minmax(210px,1fr) minmax(250px,1.1fr) auto;gap:12px;align-items:center;padding:12px;border:1px solid #29464e;border-radius:12px;background:#07181d}.umIdentity b,.umIdentity span,.umIdentity small{display:block}.umIdentity span{font-size:10px;color:#a6b8bb;margin-top:3px}.umIdentity small{font-size:8px;color:#6f888d;margin-top:4px}.umGrants{display:flex;gap:5px;flex-wrap:wrap}.grant{display:inline-flex;align-items:center;gap:5px;padding:5px 7px;border-radius:999px;border:1px solid #45616a;font:800 8px ui-monospace;color:#cbd8d9}.grant.subscription,.grant.payment{border-color:#88713d;color:#f0d789}.grant.trial{border-color:#476a78;color:#87d9e7}.grant.admin{border-color:#6a5485;color:#cab4ed}.grant.none{opacity:.5}.grant button{border:0;background:transparent;color:#e59c96;cursor:pointer;font-size:14px}.umActions{display:flex;gap:5px}.umActions button{border:1px solid #385862;background:#0b252c;color:#dce7e5;border-radius:7px;padding:6px 7px;font-size:8px;cursor:pointer}.umActions button:disabled{opacity:.45}@media(max-width:950px){.umGrid{grid-template-columns:1fr}.umUser{grid-template-columns:1fr}.umHero{display:block}.umHero>a{margin-top:14px}}`}</style>
  </div>
}
