from pathlib import Path


def once(text, old, new, label):
    if old not in text:
        raise RuntimeError(f'missing pattern: {label}')
    return text.replace(old, new, 1)

p=Path('components/admin/visual-studio.tsx')
s=p.read_text()
s=once(s,"import { TIME_OPTIONS, WEATHER_OPTIONS } from '@/lib/game/visual-contract';","import { TIME_OPTIONS, WEATHER_OPTIONS } from '@/lib/game/visual-contract';\nimport { directionalChibiSvg, type Facing } from '@/lib/game/character-directional-v3';\nimport { sceneSvg } from '@/lib/game/scene-assets-v3';\nimport { svgUri } from '@/lib/game/studio-assets';",'preview imports')
s=s.replace("camera_zoom:s.visual?.camera_zoom||1.08","camera_zoom:s.visual?.camera_zoom||1",1)

old="""            <div className=\"sceneControls\"><label>Preset<select value={v.preset||''} onChange={e=>updateStage(s.id,{preset:e.target.value})}>{presets.map(p=><option key={p.slug} value={p.slug}>{p.name}</option>)}</select></label><label>Horário<select value={v.time||'auto'} onChange={e=>updateStage(s.id,{time:e.target.value})}>{TIME_OPTIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>Clima<select value={v.weather||'auto'} onChange={e=>updateStage(s.id,{weather:e.target.value})}>{WEATHER_OPTIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>Densidade<select value={v.density||'rich'} onChange={e=>updateStage(s.id,{density:e.target.value})}><option value=\"clean\">clean</option><option value=\"balanced\">balanced</option><option value=\"rich\">rich</option></select></label><label className=\"cameraControl\">Câmera <span>{Number(v.camera_zoom||1).toFixed(2)}×</span><input type=\"range\" min=\"0.94\" max=\"1.06\" step=\"0.01\" value={Number(v.camera_zoom||1)} onChange={e=>updateStage(s.id,{camera_zoom:Number(e.target.value)})}/></label></div>
            <div className=\"actorSection\">"""
new="""            <div className={`stagePreview ${v.time||'auto'} ${v.weather||'auto'}`} style={{['--stageZoom' as any]:Number(v.camera_zoom||1)}}><img className=\"stagePreviewBg\" src={svgUri(sceneSvg(s.environment||'parking_night'))} alt=\"\"/>{(s.actors||[]).slice(0,6).map((a:any)=>{const av=actorVisuals[s.id]?.[a.id]||{archetype:a.visual?.archetype||a.style||'civilian',facing:a.visual?.facing||'front'};const left=Math.max(6,Math.min(94,Number(a.position?.x||600)/12)),top=Math.max(22,Math.min(82,Number(a.position?.y||380)/7.6));return <div className=\"stagePreviewActor\" key={a.id} style={{left:`${left}%`,top:`${top}%`}}><img src={svgUri(directionalChibiSvg(av.archetype,(av.facing||'front') as Facing))} alt=\"\"/><span>{a.name}</span></div>})}<div className=\"stagePreviewLegend\"><b>{v.preset||fallback(s.environment)}</b><span>{v.time||'auto'} • {v.weather||'auto'} • {Number(v.camera_zoom||1).toFixed(2)}×</span></div></div>
            <div className=\"sceneControls\"><label>Preset<select value={v.preset||''} onChange={e=>updateStage(s.id,{preset:e.target.value})}>{presets.map(p=><option key={p.slug} value={p.slug}>{p.name}</option>)}</select></label><label>Horário<select value={v.time||'auto'} onChange={e=>updateStage(s.id,{time:e.target.value})}>{TIME_OPTIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>Clima<select value={v.weather||'auto'} onChange={e=>updateStage(s.id,{weather:e.target.value})}>{WEATHER_OPTIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>Densidade<select value={v.density||'rich'} onChange={e=>updateStage(s.id,{density:e.target.value})}><option value=\"clean\">clean</option><option value=\"balanced\">balanced</option><option value=\"rich\">rich</option></select></label><label className=\"cameraControl\">Câmera <span>{Number(v.camera_zoom||1).toFixed(2)}×</span><input type=\"range\" min=\"0.94\" max=\"1.06\" step=\"0.01\" value={Number(v.camera_zoom||1)} onChange={e=>updateStage(s.id,{camera_zoom:Number(e.target.value)})}/></label></div>
            <div className=\"actorSection\">"""
s=once(s,old,new,'stage real preview')

old="""<div className={`actorIcon ${av.archetype}`}><i/><b/></div><div><strong>{a.name}</strong><span>{a.role||'NPC'}</span></div>"""
new="""<div className=\"actorIcon\"><img src={svgUri(directionalChibiSvg(av.archetype,(av.facing||'front') as Facing))} alt=\"\"/></div><div><strong>{a.name}</strong><span>{a.role||'NPC'}</span></div>"""
s=once(s,old,new,'real actor preview')

old=".actorIcon{width:44px;height:52px;position:relative;border-radius:9px;background:radial-gradient(circle,#1c3b44,#09171b)}.actorIcon i{position:absolute;width:25px;height:25px;border-radius:50%;left:9px;top:5px;background:#d9aa83;border:2px solid #35261f}.actorIcon b{position:absolute;width:28px;height:25px;border-radius:7px;left:8px;top:28px;background:#315d82}"
new=".actorIcon{width:50px;height:60px;position:relative;border-radius:9px;background:radial-gradient(circle,#1c3b44,#09171b);overflow:hidden}.actorIcon img{width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 8px 9px #0008)}.stagePreview{height:230px;position:relative;overflow:hidden;border-bottom:1px solid #26444d;background:#061318}.stagePreviewBg{position:absolute;inset:-3%;width:106%;height:106%;object-fit:cover;transform:scale(var(--stageZoom,1));transition:transform .2s ease}.stagePreview:after{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(180deg,#0001 45%,#02080bd9 100%)}.stagePreview.night:before{content:'';position:absolute;inset:0;z-index:1;background:#04274255;mix-blend-mode:multiply}.stagePreview.sunset:before{content:'';position:absolute;inset:0;z-index:1;background:#dd823839;mix-blend-mode:screen}.stagePreview.rain:before{content:'';position:absolute;inset:-30%;z-index:2;background:repeating-linear-gradient(105deg,transparent 0 18px,#b9edff18 19px 20px);transform:translateX(-10%);pointer-events:none}.stagePreviewActor{position:absolute;z-index:4;transform:translate(-50%,-72%);display:grid;justify-items:center;pointer-events:none}.stagePreviewActor img{width:48px;height:66px;object-fit:contain;filter:drop-shadow(0 7px 8px #000a)}.stagePreviewActor span{margin-top:-5px;padding:2px 5px;border:1px solid #41616a;border-radius:5px;background:#031015df;color:#e9f2f1;font:800 6px ui-monospace;white-space:nowrap}.stagePreviewLegend{position:absolute;z-index:5;left:11px;right:11px;bottom:9px;display:flex;justify-content:space-between;align-items:end;gap:10px}.stagePreviewLegend b{font-size:9px;color:#f0cf72}.stagePreviewLegend span{font:800 7px ui-monospace;color:#91a5a9}"
s=once(s,old,new,'studio preview css')
p.write_text(s)
