from pathlib import Path

p=Path('components/game-runtime-pro-v4.tsx')
s=p.read_text()

old_start="    startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;const d=Math.hypot(go.x-this.player.x,go.y-this.player.y);const speed=Math.max(320,Math.min(650,d/1.8));this.autoTarget={type,id,go,speed,jqDistanceAwareWalk:true};this.autoOpenLock=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`)}"
new_start="    startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;const dx=go.x-this.player.x,dy=go.y-this.player.y,d=Math.max(1,Math.hypot(dx,dy)),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78),stop=Math.min(Math.max(58,radius*.72),Math.max(58,d-2)),travel=Math.max(0,d-stop),duration=Math.max(650,Math.min(2600,700+travel*2.1)),ux=dx/d,uy=dy/d;this.player.body.setVelocity(0,0);this.autoTarget={type,id,go,fromX:this.player.x,fromY:this.player.y,toX:go.x-ux*stop,toY:go.y-uy*stop,duration,startedAt:this.time.now,jqTimedWalk:true};this.autoOpenLock=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`)}"
if old_start not in s: raise RuntimeError('startAuto anchor missing')
s=s.replace(old_start,new_start,1)

old_manual="      if(!blockedRef.current&&len>.05){this.autoTarget=null;this.player.body.setVelocity(kx/len*MANUAL_SPEED,ky/len*MANUAL_SPEED);this.faceMove(kx,ky,time)}"
new_manual="      if(!blockedRef.current&&len>.05){this.autoTarget=null;this.player.body.setVelocity(kx/len*MANUAL_SPEED,ky/len*MANUAL_SPEED);this.faceMove(kx,ky,time)}"
if old_manual not in s: raise RuntimeError('manual anchor missing')

old_auto="      else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,dx=t.go.x-this.player.x,dy=t.go.y-this.player.y,d=Math.hypot(dx,dy),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78);if(d>radius){this.player.body.setVelocity(dx/d*(t.speed||WALK_SPEED),dy/d*(t.speed||WALK_SPEED));this.faceMove(dx,dy,time);const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(260,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}}"
new_auto="      else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,elapsed=Math.max(0,time-Number(t.startedAt||time)),progress=Math.min(1,elapsed/Math.max(1,Number(t.duration||1200))),ease=1-Math.pow(1-progress,3),nx=t.fromX+(t.toX-t.fromX)*ease,ny=t.fromY+(t.toY-t.fromY)*ease,mdx=t.toX-t.fromX,mdy=t.toY-t.fromY;this.player.body.setVelocity(0,0);this.player.setPosition(nx,ny);this.faceMove(mdx,mdy,time);const d=Math.hypot(t.go.x-this.player.x,t.go.y-this.player.y),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78),meters=Math.max(1,Math.round(d/55));if(progress<1&&d>radius){if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.player.setPosition(t.toX,t.toY);this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(180,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}}"
if old_auto not in s: raise RuntimeError('auto movement anchor missing')
s=s.replace(old_auto,new_auto,1)

p.write_text(s)
