from pathlib import Path
p=Path('components/game-runtime-pro-v4.tsx')
s=p.read_text()
s=s.replace("player:any;actors:Record<string,any>={};objects:Record<string,any>={};keys:any;cursors:any;worldW=DW;worldH=DH;isDesktop=true;beacon:any;guide:any;targetBadge:any;lastNear='';lastDistance=-1;rain:any[]=[];dust:any[]=[];autoTarget:any=null;autoOpenLock=false;","player:any;actors:Record<string,any>={};objects:Record<string,any>={};keys:any;cursors:any;worldW=DW;worldH=DH;isDesktop=true;beacon:any;guide:any;targetBadge:any;lastNear='';lastDistance=-1;rain:any[]=[];dust:any[]=[];autoTarget:any=null;autoTween:any=null;autoOpenLock=false;")
old="startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;const d=Math.hypot(go.x-this.player.x,go.y-this.player.y);const speed=Math.max(320,Math.min(650,d/1.8));this.autoTarget={type,id,go,speed,jqDistanceAwareWalk:true};this.autoOpenLock=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`)}"
new="startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;if(this.autoTween){try{this.autoTween.stop()}catch{}this.autoTween=null}const sx=this.player.x,sy=this.player.y,dx=go.x-sx,dy=go.y-sy,d=Math.max(1,Math.hypot(dx,dy)),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78),travel=Math.max(0,d-radius*.76),duration=Math.round(Math.max(900,Math.min(2400,780+travel*1.55))),destX=go.x-dx/d*radius*.72,destY=go.y-dy/d*radius*.72;this.autoTarget={type,id,go,jqTimedWalk:true};this.autoOpenLock=false;this.player.body.setVelocity(0,0);this.player.body.moves=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`);this.autoTween=this.tweens.add({targets:this.player,x:destX,y:destY,duration,ease:'Sine.easeInOut',onComplete:()=>{const t=this.autoTarget;this.autoTween=null;this.player.body.moves=true;this.player.body.reset(this.player.x,this.player.y);this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);if(!t||t.id!==id||t.type!==type)return;this.autoTarget=null;const pulse=this.add.circle(go.x,go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type,id};this.lastNear=`${type}:${id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(180,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}})}"
if old not in s: raise RuntimeError('startAuto anchor missing')
s=s.replace(old,new,1)
old2="if(!blockedRef.current&&len>.05){this.autoTarget=null;this.player.body.setVelocity(kx/len*MANUAL_SPEED,ky/len*MANUAL_SPEED);this.faceMove(kx,ky,time)}"
new2="if(!blockedRef.current&&len>.05){if(this.autoTween){try{this.autoTween.stop()}catch{}this.autoTween=null;this.player.body.moves=true;this.player.body.reset(this.player.x,this.player.y)}this.autoTarget=null;this.player.body.setVelocity(kx/len*MANUAL_SPEED,ky/len*MANUAL_SPEED);this.faceMove(kx,ky,time)}"
if old2 not in s: raise RuntimeError('manual anchor missing')
s=s.replace(old2,new2,1)
start="else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,dx=t.go.x-this.player.x,dy=t.go.y-this.player.y,d=Math.hypot(dx,dy),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78);if(d>radius){this.player.body.setVelocity(dx/d*(t.speed||WALK_SPEED),dy/d*(t.speed||WALK_SPEED));this.faceMove(dx,dy,time);const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(260,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}}"
repl="else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,dx=t.go.x-this.player.x,dy=t.go.y-this.player.y,d=Math.max(1,Math.hypot(dx,dy));this.player.body.setVelocity(0,0);this.faceMove(dx,dy,time);const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}"
if start not in s: raise RuntimeError('auto update anchor missing')
s=s.replace(start,repl,1)
p.write_text(s)
