from pathlib import Path
import re

p=Path('components/game-runtime-pro-v4.tsx')
s=p.read_text()
new_start="""    startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;const dx=go.x-this.player.x,dy=go.y-this.player.y,d=Math.max(1,Math.hypot(dx,dy)),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78),travel=Math.max(0,d-radius),duration=Math.max(560,Math.min(2200,620+travel*2.05)),endX=this.player.x+dx*(travel/d),endY=this.player.y+dy*(travel/d);this.player.body.setVelocity(0,0);this.autoTarget={type,id,go,startX:this.player.x,startY:this.player.y,endX,endY,startedAt:this.time.now,duration};this.autoOpenLock=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`)}
"""
s,n=re.subn(r"    startAuto\(type:'actor'\|'object',id:string,go:any\)\{.*?\}\n    actor\(",new_start+"    actor(",s,count=1,flags=re.S)
if n!=1: raise RuntimeError(f'startAuto replace count={n}')
old2="""      else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,dx=t.go.x-this.player.x,dy=t.go.y-this.player.y,d=Math.hypot(dx,dy),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78);if(d>radius){this.player.body.setVelocity(dx/d*(t.speed||WALK_SPEED),dy/d*(t.speed||WALK_SPEED));this.faceMove(dx,dy,time);const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(260,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}}"""
new2="""      else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,p=Math.max(0,Math.min(1,(time-t.startedAt)/Math.max(1,t.duration))),eased=1-Math.pow(1-p,3),nx=t.startX+(t.endX-t.startX)*eased,ny=t.startY+(t.endY-t.startY)*eased,dx=t.endX-this.player.x,dy=t.endY-this.player.y;this.player.body.setVelocity(0,0);this.player.setPosition(nx,ny);this.player.body.updateFromGameObject?.();if(p<1){this.faceMove(dx,dy,time);const remain=Math.hypot(t.endX-nx,t.endY-ny),meters=Math.max(1,Math.round(remain/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(180,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}}"""
if old2 not in s: raise RuntimeError('update autowalk anchor missing')
s=s.replace(old2,new2,1)
p.write_text(s)

q=Path('qa/user-flow.spec.mjs')
t=q.read_text().replace("ms>=250&&ms<10000,'Clique gera caminhada perceptível'","ms>=250&&ms<6000,'Clique gera caminhada perceptível'").replace("ms>=250&&ms<10000,'Campanha usa a mesma caminhada do Plantão'","ms>=250&&ms<6000,'Campanha usa a mesma caminhada do Plantão'")
q.write_text(t)
