from pathlib import Path

p=Path('components/game-runtime-pro-v4.tsx')
s=p.read_text()
old="startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;const d=Math.hypot(go.x-this.player.x,go.y-this.player.y);const speed=Math.max(320,Math.min(650,d/1.8));this.autoTarget={type,id,go,speed,jqDistanceAwareWalk:true};this.autoOpenLock=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`)}"
new="startAuto(type:'actor'|'object',id:string,go:any){if(!this.canClick(type,id))return;const sx=this.player.x,sy=this.player.y,dx=go.x-sx,dy=go.y-sy,d=Math.max(1,Math.hypot(dx,dy)),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78),travel=Math.max(0,d-radius),ux=dx/d,uy=dy/d,endX=go.x-ux*radius,endY=go.y-uy*radius,duration=Math.max(700,Math.min(2600,travel*2.15));this.player.body.setVelocity(0,0);this.autoTarget={type,id,go,startX:sx,startY:sy,endX,endY,startedAt:performance.now(),duration,jqWallClockWalk:true};this.autoOpenLock=false;setCloud(`Indo até ${type==='actor'?'o personagem':'a evidência'}…`)}"
if old not in s:
    raise RuntimeError('startAuto anchor not found')
s=s.replace(old,new,1)
old2="else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,dx=t.go.x-this.player.x,dy=t.go.y-this.player.y,d=Math.hypot(dx,dy),radius=Math.max(72,Number(runtimeSettings?.settings?.interaction_radius||120)*.78);if(d>radius){this.player.body.setVelocity(dx/d*(t.speed||WALK_SPEED),dy/d*(t.speed||WALK_SPEED));this.faceMove(dx,dy,time);const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}}else{this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(260,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}}"
new2="else if(!blockedRef.current&&this.autoTarget){const t=this.autoTarget,elapsed=Math.max(0,performance.now()-Number(t.startedAt||0)),raw=Math.min(1,elapsed/Math.max(1,Number(t.duration||900))),ease=raw<.5?2*raw*raw:1-Math.pow(-2*raw+2,2)/2,nx=Number(t.startX)+(Number(t.endX)-Number(t.startX))*ease,ny=Number(t.startY)+(Number(t.endY)-Number(t.startY))*ease;this.player.body.setVelocity(0,0);this.player.setPosition(nx,ny);this.player.body.reset(nx,ny);const dx=t.go.x-nx,dy=t.go.y-ny,d=Math.hypot(dx,dy);this.faceMove(dx,dy,time);const meters=Math.max(1,Math.round(d/55));if(meters!==this.lastDistance){this.lastDistance=meters;setDistance(meters)}if(raw>=1){this.player.body.setVelocity(0,0);this.player.angle=0;const base=Number(this.player.jqBaseScale||this.player.scaleX||.5);this.player.setScale(base);this.autoTarget=null;const pulse=this.add.circle(t.go.x,t.go.y,24,0xe7c15c,.08).setStrokeStyle(3,0xe7c15c,.92).setDepth(1750);this.tweens.add({targets:pulse,scale:2.15,alpha:0,duration:420,ease:'Cubic.easeOut',onComplete:()=>pulse.destroy()});const next:Near={type:t.type,id:t.id};this.lastNear=`${t.type}:${t.id}`;nr.current=next;setNear(next);setDistance(null);setCloud('Alvo alcançado • abrindo interação…');if(!this.autoOpenLock){this.autoOpenLock=true;this.time.delayedCall(180,()=>{this.autoOpenLock=false;if(!blockedRef.current)primaryRef.current()})}}}"
if old2 not in s:
    raise RuntimeError('update auto walk anchor not found')
s=s.replace(old2,new2,1)
p.write_text(s)
